from django.urls import path
from .views import (
    ActualizarCuotaInscripcionView,
    ActualizarMensualidadesView,
    AuditoriaDiariaView,
    BancoDetailView,
    BancosAdminView,
    BancosListView,
    BuscarAlumnoCobranzaView,
    ClasificacionPagoCreateView,
    ClasificacionPagoDetailView,
    ComprobanteDetalleView,
    ConfiguracionCobranzaView,
    ConfigNominaView,
    ConsultaComprobantesView,
    ConsultaSolvenciaView,
    CuotaInscripcionAlumnoView,
    DashboardStatsView,
    DesgloseContableView,
    EmitirSolvenciaManualView,
    EstadoClasificacionPagosView,
    ExportarAuditoriaExcelView,
    ExportarMorososExcelView,
    ExtraerPdfConciliacionView,
    HistoricoMensualView,
    ListaMorososView,
    LoteRevisionCajaDetailView,
    LoteRevisionCajaListCreateView,
    MensualidadesAlumnoView,
    MensualidadesPuntualidadView,
    PagosListView,
    ReciboView,
    RegistrarPagoView,
    RepresentantesResumenFinancieroView,
    ResumenConciliacionView,
    SincronizarTasaView,
)

urlpatterns = [
    path('sincronizar-tasa/',              SincronizarTasaView.as_view(),          name='sincronizar-tasa'),
    path('stats/',                         DashboardStatsView.as_view(),           name='cobranza-stats'),
    path('bancos/',                        BancosListView.as_view(),               name='bancos-list'),
    path('buscar/<str:cedula>/',           BuscarAlumnoCobranzaView.as_view(),     name='buscar-alumno-cobranza'),
    path('cuota-inscripcion-alumno/<int:alumno_id>/', CuotaInscripcionAlumnoView.as_view(), name='cuota-inscripcion-alumno'),
    path('mensualidades-alumno/<int:alumno_id>/', MensualidadesAlumnoView.as_view(), name='mensualidades-alumno'),
    path('registrar-pago/',               RegistrarPagoView.as_view(),             name='registrar-pago'),
    path('recibo/<int:pago_id>/',          ReciboView.as_view(),                   name='recibo-pago'),
    path('auditoria-diaria/',              AuditoriaDiariaView.as_view(),          name='auditoria-diaria'),
    path('configuracion/',                 ConfiguracionCobranzaView.as_view(),    name='cobranza-configuracion'),
    path('actualizar-mensualidades/',      ActualizarMensualidadesView.as_view(),  name='actualizar-mensualidades'),
    path('actualizar-cuota-inscripcion/',  ActualizarCuotaInscripcionView.as_view(), name='actualizar-cuota-inscripcion'),
    path('bancos/admin/',                  BancosAdminView.as_view(),              name='bancos-admin'),
    path('bancos/admin/<int:pk>/',         BancoDetailView.as_view(),              name='banco-detail'),
    path('exportar-excel/',                ExportarAuditoriaExcelView.as_view(),   name='exportar-auditoria-excel'),
    path('historico-mensual/',             HistoricoMensualView.as_view(),         name='historico-mensual'),
    path('comprobantes/',                  ConsultaComprobantesView.as_view(),     name='consulta-comprobantes'),
    path('comprobantes/<str:factura_id>/', ComprobanteDetalleView.as_view(),       name='comprobante-detalle'),
    path('pagos/lista/',                   PagosListView.as_view(),                name='pagos-lista'),
    path('mensualidades/puntualidad/',     MensualidadesPuntualidadView.as_view(), name='mensualidades-puntualidad'),
    path('morosos/',                       ListaMorososView.as_view(),             name='morosos-dinamico'),
    path('morosos/exportar-excel/',        ExportarMorososExcelView.as_view(),     name='morosos-exportar-excel'),
    path('config-nomina/',                 ConfigNominaView.as_view(),             name='config-nomina'),
    path('solvencia/',                     ConsultaSolvenciaView.as_view(),        name='consulta-solvencia'),
    path('solvencia/manual/',              EmitirSolvenciaManualView.as_view(),    name='emitir-solvencia-manual'),
    path('conciliacion/resumen/',           ResumenConciliacionView.as_view(),       name='conciliacion-resumen'),
    path('conciliacion/lotes/',             LoteRevisionCajaListCreateView.as_view(), name='conciliacion-lotes'),
    path('conciliacion/lotes/<int:pk>/',    LoteRevisionCajaDetailView.as_view(),     name='conciliacion-lote-detalle'),
    path('conciliacion/extraer-pdf/',       ExtraerPdfConciliacionView.as_view(),     name='conciliacion-extraer-pdf'),
    path('representantes/resumen-financiero/', RepresentantesResumenFinancieroView.as_view(), name='representantes-resumen-financiero'),
    path('pagos/estado-clasificacion/',    EstadoClasificacionPagosView.as_view(), name='estado-clasificacion-pagos'),
    path('pagos/<int:pago_id>/clasificacion/', ClasificacionPagoCreateView.as_view(), name='clasificacion-pago-crear'),
    path('pagos/clasificacion/<int:linea_id>/', ClasificacionPagoDetailView.as_view(), name='clasificacion-pago-detalle'),
    path('pagos/desglose-contable/',       DesgloseContableView.as_view(),         name='desglose-contable'),
]