from django.urls import path
from .views import (
    ActualizarCuotaInscripcionView,
    ActualizarMensualidadesView,
    AuditoriaDiariaView,
    BancoDetailView,
    BancosAdminView,
    BancosListView,
    BuscarAlumnoCobranzaView,
    CargarPagoRetroactivoView,
    ClasificacionPagoBatchCreateView,
    ClasificacionPagoCreateView,
    ClasificacionPagoDetailView,
    ComprobanteDetalleView,
    AnularPagoView,
    ConfiguracionCobranzaView,
    ConfigNominaView,
    ConsultaComprobantesView,
    ConsultaSolvenciaView,
    CorregirPagoView,
    CuotaInscripcionAlumnoView,
    DashboardStatsView,
    DesgloseContableView,
    EmitirSolvenciaManualView,
    EstadoClasificacionPagosView,
    ExportarAuditoriaExcelView,
    ExportarMorososExcelView,
    ExtraerPdfConciliacionView,
    HistoricoMensualView,
    ListaMorososView,
    LoteRevisionCajaDetailView,
    LoteRevisionCajaListCreateView,
    MensualidadesAlumnoView,
    MensualidadesPuntualidadView,
    PagosListView,
    ReciboView,
    RegistrarPagoView,
    ReglaRecargoPagoViewSet,
    ReporteCostoBecasView,
    RepresentantesResumenFinancieroView,
    ResumenConciliacionView,
    SincronizarTasaView,
    TasaPorFechaView,
    TipoCargoEspecialDetailView,
    TipoCargoEspecialListCreateView,
)
from .solvencia_reportes import (
    ConceptosCobrablesView,
    EstadoCuentaRepresentanteView,
    EstadoPorConceptoView,
    ExportarEstadoPorConceptoExcelView,
    ResumenPorConceptoView,
    SolvenciaMensualView,
)

_reglas_recargo_list = ReglaRecargoPagoViewSet.as_view({'get': 'list', 'post': 'create'})
_reglas_recargo_detail = ReglaRecargoPagoViewSet.as_view({
    'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy',
})

urlpatterns = [
    path('sincronizar-tasa/',              SincronizarTasaView.as_view(),          name='sincronizar-tasa'),
    path('stats/',                         DashboardStatsView.as_view(),           name='cobranza-stats'),
    path('bancos/',                        BancosListView.as_view(),               name='bancos-list'),
    path('buscar/<str:cedula>/',           BuscarAlumnoCobranzaView.as_view(),     name='buscar-alumno-cobranza'),
    path('cuota-inscripcion-alumno/<int:alumno_id>/', CuotaInscripcionAlumnoView.as_view(), name='cuota-inscripcion-alumno'),
    path('mensualidades-alumno/<int:alumno_id>/', MensualidadesAlumnoView.as_view(), name='mensualidades-alumno'),
    path('registrar-pago/',               RegistrarPagoView.as_view(),             name='registrar-pago'),
    path('recibo/<int:pago_id>/',          ReciboView.as_view(),                   name='recibo-pago'),
    path('auditoria-diaria/',              AuditoriaDiariaView.as_view(),          name='auditoria-diaria'),
    path('configuracion/',                 ConfiguracionCobranzaView.as_view(),    name='cobranza-configuracion'),
    path('actualizar-mensualidades/',      ActualizarMensualidadesView.as_view(),  name='actualizar-mensualidades'),
    path('actualizar-cuota-inscripcion/',  ActualizarCuotaInscripcionView.as_view(), name='actualizar-cuota-inscripcion'),
    path('bancos/admin/',                  BancosAdminView.as_view(),              name='bancos-admin'),
    path('bancos/admin/<int:pk>/',         BancoDetailView.as_view(),              name='banco-detail'),
    path('exportar-excel/',                ExportarAuditoriaExcelView.as_view(),   name='exportar-auditoria-excel'),
    path('historico-mensual/',             HistoricoMensualView.as_view(),         name='historico-mensual'),
    path('comprobantes/',                  ConsultaComprobantesView.as_view(),     name='consulta-comprobantes'),
    path('comprobantes/<str:factura_id>/', ComprobanteDetalleView.as_view(),       name='comprobante-detalle'),
    path('pagos/lista/',                   PagosListView.as_view(),                name='pagos-lista'),
    path('mensualidades/puntualidad/',     MensualidadesPuntualidadView.as_view(), name='mensualidades-puntualidad'),
    path('morosos/',                       ListaMorososView.as_view(),             name='morosos-dinamico'),
    path('morosos/exportar-excel/',        ExportarMorososExcelView.as_view(),     name='morosos-exportar-excel'),
    path('config-nomina/',                 ConfigNominaView.as_view(),             name='config-nomina'),
    path('solvencia/',                     ConsultaSolvenciaView.as_view(),        name='consulta-solvencia'),
    path('solvencia/manual/',              EmitirSolvenciaManualView.as_view(),    name='emitir-solvencia-manual'),
    path('conciliacion/resumen/',           ResumenConciliacionView.as_view(),       name='conciliacion-resumen'),
    path('conciliacion/lotes/',             LoteRevisionCajaListCreateView.as_view(), name='conciliacion-lotes'),
    path('conciliacion/lotes/<int:pk>/',    LoteRevisionCajaDetailView.as_view(),     name='conciliacion-lote-detalle'),
    path('conciliacion/extraer-pdf/',       ExtraerPdfConciliacionView.as_view(),     name='conciliacion-extraer-pdf'),
    path('representantes/resumen-financiero/', RepresentantesResumenFinancieroView.as_view(), name='representantes-resumen-financiero'),
    path('pagos/estado-clasificacion/',    EstadoClasificacionPagosView.as_view(), name='estado-clasificacion-pagos'),
    path('pagos/<int:pago_id>/clasificacion/', ClasificacionPagoCreateView.as_view(), name='clasificacion-pago-crear'),
    path('pagos/clasificacion/batch/',     ClasificacionPagoBatchCreateView.as_view(), name='clasificacion-pago-batch'),
    path('pagos/clasificacion/<int:linea_id>/', ClasificacionPagoDetailView.as_view(), name='clasificacion-pago-detalle'),
    path('pagos/desglose-contable/',       DesgloseContableView.as_view(),         name='desglose-contable'),
    path('pagos/<int:pago_id>/corregir/',  CorregirPagoView.as_view(),             name='corregir-pago'),
    path('pagos/<int:pago_id>/anular/',    AnularPagoView.as_view(),               name='anular-pago'),
    path('pagos/retroactivo/',             CargarPagoRetroactivoView.as_view(),    name='cargar-pago-retroactivo'),
    path('tasa/por-fecha/',                TasaPorFechaView.as_view(),             name='tasa-por-fecha'),
    path('tipos-cargo-especial/',          TipoCargoEspecialListCreateView.as_view(), name='tipos-cargo-especial'),
    path('tipos-cargo-especial/<int:pk>/', TipoCargoEspecialDetailView.as_view(),  name='tipo-cargo-especial-detalle'),
    path('reporte-becas/',                 ReporteCostoBecasView.as_view(),        name='reporte-costo-becas'),
    path('reglas-recargo-pago/',           _reglas_recargo_list,                   name='reglas-recargo-pago-list'),
    path('reglas-recargo-pago/<int:pk>/',  _reglas_recargo_detail,                 name='reglas-recargo-pago-detail'),
    path('conceptos-cobrables/',           ConceptosCobrablesView.as_view(),       name='conceptos-cobrables'),
    path('solvencia-mensual/',             SolvenciaMensualView.as_view(),         name='solvencia-mensual'),
    path('estado-por-concepto/resumen/',   ResumenPorConceptoView.as_view(),       name='estado-por-concepto-resumen'),
    path('estado-por-concepto/exportar-excel/', ExportarEstadoPorConceptoExcelView.as_view(), name='estado-por-concepto-exportar-excel'),
    path('estado-por-concepto/',           EstadoPorConceptoView.as_view(),        name='estado-por-concepto'),
    path('representantes/<int:representante_id>/estado-cuenta/', EstadoCuentaRepresentanteView.as_view(), name='representante-estado-cuenta'),
]