# Generated by Django 6.0.4 on 2026-08-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sitio/config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='sitio/config/')),
                ('color_primario', models.CharField(blank=True, default='#0fa3b1', max_length=7)),
                ('color_secundario', models.CharField(blank=True, default='#1f3864', max_length=7)),
                ('color_acento', models.CharField(blank=True, default='', max_length=7)),
                ('redes_sociales', models.JSONField(blank=True, default=dict, help_text='{facebook, instagram, twitter, youtube, tiktok} — todas opcionales')),
                ('seo_titulo_default', models.CharField(blank=True, default='', max_length=70)),
                ('seo_descripcion_default', models.CharField(blank=True, default='', max_length=160)),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=50)),
                ('email_contacto', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="ej. 'principal', 'footer'", max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_original', models.ImageField(upload_to='sitio/media/originales/')),
                ('variantes', models.JSONField(blank=True, default=dict, help_text='{thumb, sm, md, lg, original}')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('ancho_original', models.IntegerField(default=0)),
                ('alto_original', models.IntegerField(default=0)),
                ('peso_bytes', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitio_media_subida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.CharField(blank=True, default='', max_length=300)),
                ('cuerpo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], db_index=True, default='borrador', max_length=15)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('seo_titulo', models.CharField(blank=True, default='', max_length=70)),
                ('seo_descripcion', models.CharField(blank=True, default='', max_length=160)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitio_articulos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='sitio.categoria')),
                ('imagen_destacada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_destacados', to='sitio.media')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], db_index=True, default='borrador', max_length=15)),
                ('es_home', models.BooleanField(default=False)),
                ('orden_menu', models.IntegerField(default=0)),
                ('mostrar_en_menu', models.BooleanField(default=True)),
                ('seo_titulo', models.CharField(blank=True, default='', max_length=70)),
                ('seo_descripcion', models.CharField(blank=True, default='', max_length=160)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitio_paginas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['orden_menu', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('tipo_destino', models.CharField(choices=[('pagina', 'Página'), ('articulo', 'Artículo'), ('url_externa', 'URL externa')], default='pagina', max_length=15)),
                ('url_externa', models.CharField(blank=True, default='', max_length=500)),
                ('orden', models.IntegerField(default=0)),
                ('abre_nueva_pestana', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sitio.menu')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_menu', to='sitio.pagina')),
            ],
            options={
                'verbose_name': 'Item de Menú',
                'verbose_name_plural': 'Items de Menú',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hero', 'Hero'), ('texto_imagen', 'Texto + Imagen'), ('galeria', 'Galería'), ('cards', 'Cards'), ('cta', 'CTA'), ('testimonios', 'Testimonios'), ('carrusel', 'Carrusel')], max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('contenido', models.JSONField(blank=True, default=dict)),
                ('animacion', models.CharField(blank=True, choices=[('', 'Ninguna'), ('fade-in', 'Fade in'), ('slide-up', 'Slide up'), ('slide-left', 'Slide left'), ('slide-right', 'Slide right'), ('scroll-reveal', 'Scroll reveal'), ('stagger', 'Stagger'), ('parallax', 'Parallax'), ('hover-lift', 'Hover lift'), ('hover-glow', 'Hover glow'), ('zoom-on-scroll', 'Zoom on scroll')], default='', max_length=20)),
                ('config_estilo', models.JSONField(blank=True, default=dict, help_text='{ancho, espaciado_top, espaciado_bottom, fondo}')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='sitio.pagina')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
