# Generated by Django 6.0.4 on 2026-08-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_itemmenu_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Sesión de vista previa',
                'verbose_name_plural': 'Sesiones de vista previa',
            },
        ),
    ]
