# Generated by Django 6.0.4 on 2026-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_previewsesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='alineacion_menu',
            field=models.CharField(choices=[('izquierda', 'Logo izquierda, links derecha'), ('centro', 'Logo y links centrados')], default='izquierda', max_length=15),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='estilo_botones',
            field=models.CharField(choices=[('pildora', 'Píldora'), ('redondeado', 'Redondeado'), ('cuadrado', 'Cuadrado')], default='pildora', max_length=15),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='estilo_footer',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('marca', 'Color de marca')], default='claro', max_length=15),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='estilo_menu',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('marca', 'Color de marca'), ('transparente', 'Transparente sobre el hero')], default='claro', max_length=15),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='menu_fijo',
            field=models.BooleanField(default=True, help_text='Si el menú queda fijo (sticky) al hacer scroll.'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='tipografia',
            field=models.CharField(choices=[('moderna', 'Moderna (sans)'), ('editorial', 'Editorial (serif + sans)'), ('clasica', 'Clásica (serif)')], default='moderna', max_length=15),
        ),
    ]
