# Generated by Django 6.0.4 on 2026-08-20 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_configuracionsitio_alineacion_menu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Historial mínimo (Fase 2): quién hizo la última edición, sin versionado de contenido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitio_paginas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagina',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Papelera (soft-delete, Fase 2): si no es null, la página está en la papelera. Al enviarla a la papelera también se fuerza estado=borrador, así los endpoints públicos (que ya filtran por estado=publicado) la excluyen sin cambios adicionales.', null=True),
        ),
        migrations.CreateModel(
            name='PatronBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('hero', 'Hero'), ('texto_imagen', 'Texto + Imagen'), ('galeria', 'Galería'), ('cards', 'Cards'), ('cta', 'CTA'), ('testimonios', 'Testimonios'), ('carrusel', 'Carrusel')], max_length=20)),
                ('contenido', models.JSONField(blank=True, default=dict)),
                ('animacion', models.CharField(blank=True, choices=[('', 'Ninguna'), ('fade-in', 'Fade in'), ('slide-up', 'Slide up'), ('slide-left', 'Slide left'), ('slide-right', 'Slide right'), ('scroll-reveal', 'Scroll reveal'), ('stagger', 'Stagger'), ('parallax', 'Parallax'), ('hover-lift', 'Hover lift'), ('hover-glow', 'Hover glow'), ('zoom-on-scroll', 'Zoom on scroll')], default='', max_length=20)),
                ('config_estilo', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitio_patrones_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrón de bloque',
                'verbose_name_plural': 'Patrones de bloque',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('secciones', models.JSONField(blank=True, default=list, help_text='Lista congelada [{tipo, contenido, animacion, config_estilo}, ...], mismo orden que en la página de origen.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitio_plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de página',
                'verbose_name_plural': 'Plantillas de página',
                'ordering': ['-creado_en'],
            },
        ),
    ]
