# Generated by Django 6.0.4 on 2026-07-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_comprobante_antifraude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='referencia_bancaria',
            field=models.CharField(blank=True, db_index=True, help_text='Número de confirmación, referencia de pago móvil o N° de transferencia', max_length=100, null=True, verbose_name='Referencia / N° de transacción'),
        ),
    ]
