# Generated by Django 6.0.4 on 2026-08-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_comprobantepago_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representanteuser',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='True cuando la contraseña actual fue asignada por un administrador (activación o restablecimiento) y aún no ha sido cambiada por el propio representante.', verbose_name='Debe cambiar contraseña'),
        ),
    ]
