# Generated by Django 6.0.4 on 2026-09-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0039_remove_pago_unique_referencia_pago_activo_and_more'),
        ('portal', '0005_representanteuser_debe_cambiar_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comprobantepago',
            name='unique_referencia_comprobante_activo',
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='banco_receptor',
            field=models.ForeignKey(blank=True, help_text='Opcional: el portal nunca bloquea el envío por falta de banco.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='cobranza.bancoinstitucional', verbose_name='Banco receptor'),
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddConstraint(
            model_name='comprobantepago',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus__in', ['pendiente', 'aprobado'])), fields=('referencia_bancaria', 'metodo_pago', 'banco_receptor'), name='unique_referencia_comprobante_activo'),
        ),
    ]
