# Generated by Django 6.0.5 on 2026-06-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_materia_sede'),
        ('secretaria', '0008_configuracionsistema_colores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalasistencia',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Asistencia', 'verbose_name_plural': 'historical Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='historicalnota',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Nota', 'verbose_name_plural': 'historical Notas'},
        ),
        migrations.RemoveField(
            model_name='historicalasistencia',
            name='alumno_id',
        ),
        migrations.RemoveField(
            model_name='historicalasistencia',
            name='registrado_por_id',
        ),
        migrations.RemoveField(
            model_name='historicalnota',
            name='alumno_id',
        ),
        migrations.RemoveField(
            model_name='historicalnota',
            name='lapso_id',
        ),
        migrations.RemoveField(
            model_name='historicalnota',
            name='materia_id',
        ),
        migrations.AddField(
            model_name='historicalasistencia',
            name='alumno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretaria.alumno'),
        ),
        migrations.AddField(
            model_name='historicalasistencia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnota',
            name='alumno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretaria.alumno'),
        ),
        migrations.AddField(
            model_name='historicalnota',
            name='lapso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academico.lapso'),
        ),
        migrations.AddField(
            model_name='historicalnota',
            name='materia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academico.materia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='secretaria.alumno'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalnota',
            name='definitiva',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnota',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='aula',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='dia_semana',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.materia'),
        ),
        migrations.AlterField(
            model_name='lapso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lapso',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lapso',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lapso',
            name='nombre',
            field=models.CharField(choices=[('1er Lapso', '1er Lapso'), ('2do Lapso', '2do Lapso'), ('3er Lapso', '3er Lapso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lapso',
            name='periodo_escolar',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='materia',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materia',
            name='grado_seccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='secretaria.alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='definitiva',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='lapso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.lapso'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.materia'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
