# Generated by Django 6.0.4 on 2026-07-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_materia_horas_academicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
    ]
