# Generated by Django 6.0.4 on 2026-07-27 22:26

import academico.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_estado(apps, schema_editor):
    """Deriva 'estado' de los booleanos presente/justificada ya existentes.

    presente=True,justificada=False  -> 'P'
    presente=False,justificada=True  -> 'J'
    presente=False,justificada=False -> 'A'
    'R' no se backfillea: no existía antes de esta migración.
    """
    Asistencia = apps.get_model('academico', 'Asistencia')
    Asistencia.objects.filter(presente=True, justificada=False).update(estado='P')
    Asistencia.objects.filter(presente=False, justificada=True).update(estado='J')
    Asistencia.objects.filter(presente=False, justificada=False).update(estado='A')


def revertir_estado(apps, schema_editor):
    Asistencia = apps.get_model('academico', 'Asistencia')
    Asistencia.objects.update(estado=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_asistencia_fecha_and_more'),
        ('secretaria', '0016_configuracionsistema_logo_avec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('R', 'Retardado')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalasistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('R', 'Retardado')], max_length=1, null=True),
        ),
        migrations.RunPython(backfill_estado, revertir_estado),
        migrations.CreateModel(
            name='IncidenteDisciplinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('L', 'Leve'), ('M', 'Moderado'), ('G', 'Grave')], max_length=1)),
                ('adjunto', models.ImageField(blank=True, null=True, upload_to='incidentes/', validators=[academico.models.validar_tamano_adjunto])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='secretaria.alumno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente Disciplinario',
                'verbose_name_plural': 'Incidentes Disciplinarios',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
