# Generated by Django 6.0.4 on 2026-07-28 01:50

import academico.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_asistencia_estado_incidentedisciplinario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/', validators=[academico.models.validar_tamano_adjunto])),
                ('enlace', models.URLField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='academico.materia')),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material de Estudio',
                'verbose_name_plural': 'Materiales de Estudio',
                'ordering': ['-fecha'],
            },
        ),
    ]
