# Generated by Django 6.0.4 on 2026-07-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_materialestudio'),
        ('secretaria', '0016_configuracionsistema_logo_avec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umbral_minimo', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resuelta_at', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_rendimiento', to='secretaria.alumno')),
                ('lapso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_rendimiento', to='academico.lapso')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_rendimiento', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Alerta de Rendimiento',
                'verbose_name_plural': 'Alertas de Rendimiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
