# Generated by Django 6.0.5 on 2026-08-04 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_eventocalendario'),
        ('secretaria', '0016_configuracionsistema_logo_avec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('total_puntos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('modo', models.CharField(choices=[('puntos', 'Suma de puntos'), ('promedio', 'Promedio')], default='puntos', max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bloque de Evaluación',
                'verbose_name_plural': 'Bloques de Evaluación',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='aporta_a_todas_las_materias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materia',
            name='cuenta_para_promedio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='tipo_evaluacion',
            field=models.CharField(choices=[('numerica', 'Numérica'), ('literal', 'Literal (A/B/C)')], default='numerica', max_length=10),
        ),
        migrations.CreateModel(
            name='ItemEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academico.bloqueevaluacion')),
            ],
            options={
                'verbose_name': 'Ítem de Evaluación',
                'verbose_name_plural': 'Ítems de Evaluación',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lapso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_evaluacion', to='academico.lapso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_evaluacion', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Plan de Evaluación',
                'verbose_name_plural': 'Planes de Evaluación',
                'unique_together': {('materia', 'lapso')},
            },
        ),
        migrations.AddField(
            model_name='bloqueevaluacion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='academico.planevaluacion'),
        ),
        migrations.CreateModel(
            name='NotaItemEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_letra', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_item_evaluacion', to='secretaria.alumno')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.itemevaluacion')),
            ],
            options={
                'verbose_name': 'Nota de Ítem de Evaluación',
                'verbose_name_plural': 'Notas de Ítems de Evaluación',
                'unique_together': {('item', 'alumno')},
            },
        ),
    ]
