# Generated by Django 6.0.4 on 2026-08-28 14:36

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_historicalnotaitemevaluacion'),
        ('multisede', '0001_initial'),
        ('rrhh', '0009_arreglos_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_academico', models.CharField(blank=True, default='', max_length=120)),
                ('especialidad', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email_institucional', models.EmailField(blank=True, default='', max_length=254)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docente', to='rrhh.empleado')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='multisede.sede')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo_academico', models.CharField(blank=True, default='', max_length=120)),
                ('especialidad', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email_institucional', models.EmailField(blank=True, default='', max_length=254)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multisede.sede')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Docente',
                'verbose_name_plural': 'historical Docentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
