# Generated by Django 6.0.4 on 2026-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_docente_historicaldocente'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='horarioclase',
            index=models.Index(fields=['dia_semana', 'hora_inicio'], name='academico_h_dia_sem_6188fb_idx'),
        ),
    ]
