# Generated by Django 6.0.4 on 2026-09-16 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_horarioclase_academico_h_dia_sem_6188fb_idx'),
        ('multisede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10)),
                ('orden', models.PositiveSmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('clase', 'Clase'), ('receso', 'Receso')], default='clase', max_length=10)),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'ordering': ['dia_semana', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='horas_semanales_objetivo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de bloques semanales deseada (referencia, no un tope duro).', null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='horas_semanales_tope',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Máximo de bloques de 45 min que puede dictar por semana.', null=True),
        ),
        migrations.AddField(
            model_name='historicaldocente',
            name='horas_semanales_objetivo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de bloques semanales deseada (referencia, no un tope duro).', null=True),
        ),
        migrations.AddField(
            model_name='historicaldocente',
            name='horas_semanales_tope',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Máximo de bloques de 45 min que puede dictar por semana.', null=True),
        ),
        migrations.AddField(
            model_name='horarioclase',
            name='pineado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horarioclase',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='academico.bloquehorario'),
        ),
        migrations.CreateModel(
            name='DisponibilidadDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='academico.docente')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Docente',
                'verbose_name_plural': 'Disponibilidades de Docentes',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_horario_creados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_horario', to='multisede.sede')),
            ],
            options={
                'verbose_name': 'Paquete de Horario',
                'verbose_name_plural': 'Paquetes de Horario',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GeneracionHorarioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios_creados_ids', models.JSONField(default=list)),
                ('horarios_eliminados', models.JSONField(default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('deshecho', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_generacion_horario', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_generacion', to='academico.paquetehorario')),
            ],
            options={
                'verbose_name': 'Snapshot de Generación de Horario',
                'verbose_name_plural': 'Snapshots de Generación de Horario',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='academico.paquetehorario'),
        ),
        migrations.AlterUniqueTogether(
            name='bloquehorario',
            unique_together={('paquete', 'dia_semana', 'orden')},
        ),
        migrations.CreateModel(
            name='PaqueteHorarioGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_seccion', models.CharField(max_length=50)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='academico.paquetehorario')),
            ],
            options={
                'verbose_name': 'Grado de Paquete de Horario',
                'verbose_name_plural': 'Grados de Paquete de Horario',
                'unique_together': {('paquete', 'grado_seccion')},
            },
        ),
    ]
