# Generated by Django 6.0.4 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_bloquehorario_docente_horas_semanales_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquehorario',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('clase', 'Clase'),
                    ('receso', 'Receso'),
                    ('inicio', 'Inicio / entonación del himno'),
                ],
                default='clase',
                max_length=10,
            ),
        ),
    ]
