# Generated by Django 6.0.4 on 2026-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_bloquehorario_tipo_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalasistencia',
            name='actualizado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
