# Generated by Django 6.0.4 on 2026-08-13 16:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0029_alter_historicalpago_fecha_pago_and_more'),
        ('secretaria', '0016_configuracionsistema_logo_avec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_credito_default', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('dias_alerta_saldo_negativo', models.CharField(default='1,3,7', help_text='Días de saldo negativo sostenido en que se envía recordatorio, separados por coma.', max_length=50)),
            ],
            options={
                'verbose_name': 'Parámetro de Cantina',
                'verbose_name_plural': 'Parámetros de Cantina',
            },
        ),
        migrations.CreateModel(
            name='LoteTarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cantina/productos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='cantina.categoriaproducto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaPrepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=20, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('extraviada', 'Extraviada')], default='sin_asignar', max_length=15)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('saldo_negativo_desde', models.DateField(blank=True, null=True)),
                ('asignada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_cantina', to='secretaria.alumno')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas', to='cantina.lotetarjetas')),
            ],
        ),
        migrations.CreateModel(
            name='RecargaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=20)),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto captado en divisas (canónico)', max_digits=10)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, help_text='Tasa BCV vigente al momento de la recarga (snapshot de cobranza.TasaCambio)', max_digits=12)),
                ('monto_ves', models.DecimalField(decimal_places=2, editable=False, help_text='Equivalente contable en Bolívares', max_digits=20)),
                ('banco_procedencia', models.CharField(blank=True, help_text='Banco emisor del pagador (transferencia/pago móvil)', max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_lote', models.CharField(blank=True, help_text='Solo Punto de Venta — 4 dígitos, igual que cobranza', max_length=10, null=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='cantina/comprobantes/%Y/%m/')),
                ('registrado_por_portal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('banco_receptor', models.ForeignKey(blank=True, help_text='Banco/cuenta del colegio que recibió — mismo catálogo que usa cobranza, no se duplica', null=True, on_delete=django.db.models.deletion.PROTECT, to='cobranza.bancoinstitucional')),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_cantina', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='cantina.tarjetaprepago')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCodigoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_anterior', models.CharField(max_length=50)),
                ('motivo', models.CharField(choices=[('extravio', 'Extravío'), ('dano', 'Tarjeta dañada')], max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_codigos', to='cantina.tarjetaprepago')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='VentaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('tarjeta_prepago', 'Tarjeta Prepago'), ('efectivo', 'Efectivo Divisas (USD)'), ('efectivo_ves', 'Efectivo Bolívares (VES)')], max_length=20)),
                ('total_usd', models.DecimalField(decimal_places=2, help_text='Total canónico en USD (el precio de cada producto vive en USD)', max_digits=10)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, help_text='Tasa BCV vigente al momento de la venta (snapshot de cobranza.TasaCambio) — se usa para imprimir el ticket en VES si se cobró en efectivo_ves', max_digits=12)),
                ('total_ves', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=15)),
                ('saldo_tarjeta_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_cantina', to='secretaria.alumno')),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cantina', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='cantina.tarjetaprepago')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga'), ('consumo', 'Consumo'), ('ajuste', 'Ajuste manual'), ('reverso', 'Reverso')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_antes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_despues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cantina.recargatarjeta')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cantina.tarjetaprepago')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cantina.ventacantina')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (compra a proveedor)'), ('salida', 'Salida (venta)'), ('ajuste', 'Ajuste (merma / conteo)')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('stock_antes', models.IntegerField()),
                ('stock_despues', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cantina.productocantina')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='cantina.ventacantina')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='cantina.productocantina')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cantina.ventacantina')),
            ],
        ),
        migrations.CreateModel(
            name='CierreCajaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_recargas_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('conteo_fisico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrado_en', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_cantina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('cajero', 'fecha')},
            },
        ),
        migrations.AddIndex(
            model_name='productocantina',
            index=models.Index(fields=['codigo_barras'], name='cantina_pro_codigo__c1404d_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjetaprepago',
            index=models.Index(fields=['codigo'], name='cantina_tar_codigo_1906ba_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjetaprepago',
            index=models.Index(fields=['serial'], name='cantina_tar_serial_4df061_idx'),
        ),
    ]
