# Generated by Django 6.0.4 on 2026-08-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cierrecajacantina',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='AperturaCajaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_cantina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_apertura'],
            },
        ),
        migrations.AddField(
            model_name='cierrecajacantina',
            name='apertura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='cantina.aperturacajacantina'),
        ),
        migrations.AddField(
            model_name='ventacantina',
            name='apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='cantina.aperturacajacantina'),
        ),
        migrations.AddConstraint(
            model_name='aperturacajacantina',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('cajero',), name='unica_apertura_abierta_por_cajero'),
        ),
    ]
