# Generated by Django 6.0.4 on 2026-10-06 11:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0002_alter_cierrecajacantina_unique_together_and_more'),
        ('cobranza', '0046_bancoinstitucional_portal_metodos'),
        ('secretaria', '0030_alter_configuracionsistema_abonos_parciales_requieren_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacajacantina',
            name='area',
            field=models.CharField(choices=[('cantina', 'Cantina'), ('libreria', 'Librería')], db_index=True, default='cantina', max_length=10),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='area',
            field=models.CharField(choices=[('cantina', 'Cantina'), ('libreria', 'Librería')], db_index=True, default='cantina', max_length=10),
        ),
        migrations.AddField(
            model_name='cierrecajacantina',
            name='area',
            field=models.CharField(choices=[('cantina', 'Cantina'), ('libreria', 'Librería')], db_index=True, default='cantina', max_length=10),
        ),
        migrations.AddField(
            model_name='cierrecajacantina',
            name='totales_por_metodo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parametrocantina',
            name='limite_credito_representante_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Límite de crédito (USD) por representante para ventas cargadas a cuenta (CxC).', max_digits=10),
        ),
        migrations.AddField(
            model_name='productocantina',
            name='area',
            field=models.CharField(choices=[('cantina', 'Cantina'), ('libreria', 'Librería')], db_index=True, default='cantina', max_length=10),
        ),
        migrations.AddField(
            model_name='ventacantina',
            name='area',
            field=models.CharField(choices=[('cantina', 'Cantina'), ('libreria', 'Librería')], db_index=True, default='cantina', max_length=10),
        ),
        migrations.AddField(
            model_name='ventacantina',
            name='banco_procedencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventacantina',
            name='banco_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cobranza.bancoinstitucional'),
        ),
        migrations.AddField(
            model_name='ventacantina',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventacantina',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventacantina',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cantina_credito', to='secretaria.representante'),
        ),
        migrations.AlterField(
            model_name='ventacantina',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_prepago', 'Tarjeta Prepago'), ('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares'), ('credito_representante', 'Cargo a cuenta del representante')], max_length=25),
        ),
        migrations.CreateModel(
            name='AbonoCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_uuid', models.UUIDField(db_index=True)),
                ('area', models.CharField(choices=[('cantina', 'Cantina'), ('libreria', 'Librería')], max_length=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares')], max_length=20)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=12)),
                ('monto_ves', models.DecimalField(decimal_places=2, max_digits=20)),
                ('banco_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_pago', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('es_retroactivo', models.BooleanField(default=False)),
                ('motivo', models.TextField(blank=True)),
                ('estatus', models.CharField(choices=[('completado', 'Completado'), ('anulado', 'Anulado')], default='completado', max_length=12)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_cantina_anulados', to=settings.AUTH_USER_MODEL)),
                ('apertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='cantina.aperturacajacantina')),
                ('banco_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cobranza.bancoinstitucional')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_cantina', to=settings.AUTH_USER_MODEL)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_cantina', to='secretaria.representante')),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CargoCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('cantina', 'Cantina'), ('libreria', 'Librería')], max_length=10)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_cantina', to='secretaria.alumno')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_cantina', to='secretaria.representante')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cargo', to='cantina.ventacantina')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionAbonoCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cantina.abonocantina')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='cantina.cargocantina')),
            ],
        ),
        migrations.CreateModel(
            name='CreditoRepresentanteCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_usd', models.DecimalField(blank=True, decimal_places=2, help_text='null = usa ParametroCantina.limite_credito_representante_default', max_digits=10, null=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('representante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito_cantina', to='secretaria.representante')),
            ],
        ),
        migrations.AddIndex(
            model_name='abonocantina',
            index=models.Index(fields=['representante', 'estatus'], name='cantina_abo_represe_f7d134_idx'),
        ),
        migrations.AddIndex(
            model_name='cargocantina',
            index=models.Index(fields=['representante', 'estado'], name='cantina_car_represe_7bf438_idx'),
        ),
    ]
