# Generated by Django 6.0.4 on 2026-10-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0003_cxc_y_areas'),
        ('cobranza', '0046_bancoinstitucional_portal_metodos'),
        ('secretaria', '0030_alter_configuracionsistema_abonos_parciales_requieren_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacionabonocantina',
            name='abono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='cantina.abonocantina'),
        ),
        migrations.AddIndex(
            model_name='abonocantina',
            index=models.Index(fields=['referencia', 'metodo_pago'], name='cantina_abo_referen_c1a313_idx'),
        ),
        migrations.AddIndex(
            model_name='cargocantina',
            index=models.Index(fields=['representante', 'area', 'estado'], name='cantina_car_represe_04c815_idx'),
        ),
        migrations.AddIndex(
            model_name='ventacantina',
            index=models.Index(fields=['referencia', 'metodo_pago'], name='cantina_ven_referen_3f3055_idx'),
        ),
        migrations.AddConstraint(
            model_name='abonocantina',
            constraint=models.CheckConstraint(condition=models.Q(('monto_usd__gt', 0)), name='abono_cantina_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='aplicacionabonocantina',
            constraint=models.CheckConstraint(condition=models.Q(('monto_usd__gt', 0)), name='aplicacion_abono_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cargocantina',
            constraint=models.CheckConstraint(condition=models.Q(('monto_usd__gt', 0)), name='cargo_cantina_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cargocantina',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado__gte', 0), ('monto_pagado__lte', models.F('monto_usd'))), name='cargo_cantina_pagado_en_rango'),
        ),
    ]
