import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Plus, Trash2 } from 'lucide-react';
import DatePickerES from '../DatePickerES';
import DecimalInput from '../DecimalInput';
import { TablaScroll } from '../ui/TablaScroll';
import SubirComprobantes from './SubirComprobantes';
import ProveedorRapidoModal from '../proveedores/ProveedorRapidoModal';
import { crearProveedor, listarCategorias, listarProveedores } from '../../services/finanzasService';
import { toast } from 'react-toastify';
import { parseApiError } from '../../utils/apiError';

const hoy = () => new Date().toISOString().slice(0, 10);
const lineaInicial = () => ({ descripcion: '', cantidad: '1.00', precio_unitario: '', descuento: '0.00', ultimo_precio: null });
const numero = (v) => Number(v || 0);

export default function EgresoForm({ onGuardar, guardando = false }) {
  const [datos, setDatos] = useState({ proveedor: '', categoria: '', tipo_documento: 'factura', numero_documento: '', fecha_emision: hoy(), fecha_egreso: hoy(), moneda: 'VES', tasa_aplicada: '', motivo_cambio_tasa: '', porcentaje_iva: '16.00', aplica_igtf: false, retiene_iva: false, retiene_islr: false, metodo_pago: 'transferencia', banco_pago: '', referencia_pago: '', descripcion: '', fiscal_activo: true });
  const [proveedores, setProveedores] = useState([]); const [categorias, setCategorias] = useState([]); const [renglones, setRenglones] = useState([lineaInicial()]); const [archivos, setArchivos] = useState([]); const [modalProveedor, setModalProveedor] = useState(false);
  useEffect(() => { Promise.all([listarProveedores(), listarCategorias()]).then(([p, c]) => { setProveedores(p.data.results || p.data); setCategorias(c.data.results || c.data); }).catch(() => toast.error('No se pudieron cargar proveedores o categorías.')); }, []);
  const subtotal = useMemo(() => renglones.reduce((s, r) => s + Math.max(0, numero(r.cantidad) * numero(r.precio_unitario) - numero(r.descuento)), 0), [renglones]);
  const iva = datos.fiscal_activo ? subtotal * numero(datos.porcentaje_iva) / 100 : 0;
  const total = subtotal + iva;
  const equivalente = datos.moneda === 'VES' && numero(datos.tasa_aplicada) ? total / numero(datos.tasa_aplicada) : total * numero(datos.tasa_aplicada);
  const cambiar = (event) => { const { name, value, type, checked } = event.target; setDatos((actual) => ({ ...actual, [name]: type === 'checkbox' ? checked : value })); };
  const cambiarLinea = (index, campo, value) => setRenglones((actual) => actual.map((r, i) => i === index ? { ...r, [campo]: value } : r));
  const guardarProveedor = async (proveedor) => { try { const { data } = await crearProveedor(proveedor); setProveedores((actual) => [...actual, data]); setDatos((actual) => ({ ...actual, proveedor: data.id })); toast.success('Proveedor creado.'); } catch (error) { toast.error(parseApiError(error)); throw error; } };
  const enviar = async (event) => { event.preventDefault(); if (!datos.proveedor || !datos.categoria || !renglones.some((r) => r.descripcion && numero(r.precio_unitario))) return toast.warning('Completa proveedor, categoría y al menos un renglón.'); if (datos.tasa_aplicada && datos.motivo_cambio_tasa.trim().length === 0) return toast.warning('Indica el motivo si modificaste la tasa BCV.'); await onGuardar({ ...datos, condicion: 'contado', subtotal: subtotal.toFixed(2), monto_iva: iva.toFixed(2), total_documento: total.toFixed(2), renglones, comprobantes: archivos }); };
  return <form onSubmit={enviar} className="space-y-5 pb-24 sm:pb-4"><section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 rounded-xl border p-3 sm:p-5"><label className="text-sm">Proveedor<div className="flex gap-2"><select required name="proveedor" value={datos.proveedor} onChange={cambiar} className="mt-1 min-w-0 flex-1 rounded-lg border p-2"><option value="">Selecciona</option>{proveedores.map((p) => <option key={p.id} value={p.id}>{p.razon_social}</option>)}</select><button type="button" onClick={() => setModalProveedor(true)} className="mt-1 rounded-lg border px-3" aria-label="Nuevo proveedor"><Plus size={16} /></button></div></label><label className="text-sm">Categoría<select required name="categoria" value={datos.categoria} onChange={cambiar} className="mt-1 w-full rounded-lg border p-2"><option value="">Selecciona</option>{categorias.map((c) => <option key={c.id} value={c.id}>{c.padre_nombre ? `${c.padre_nombre} › ` : ''}{c.nombre}</option>)}</select></label><label className="text-sm">Documento<input required name="numero_documento" value={datos.numero_documento} onChange={cambiar} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Fecha de emisión<DatePickerES value={datos.fecha_emision} onChange={(e) => cambiar({ target: { name: 'fecha_emision', value: e.target.value } })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Moneda<select name="moneda" value={datos.moneda} onChange={cambiar} className="mt-1 w-full rounded-lg border p-2"><option value="VES">Bolívares (VES)</option><option value="USD">Dólares (USD)</option></select></label><label className="text-sm">Tasa BCV de la fecha<DecimalInput value={datos.tasa_aplicada} onChange={(value) => setDatos((x) => ({ ...x, tasa_aplicada: value }))} className="mt-1 w-full rounded-lg border p-2" /></label>{datos.tasa_aplicada && <label className="text-sm sm:col-span-2">Motivo de cambio de tasa<input required name="motivo_cambio_tasa" value={datos.motivo_cambio_tasa} onChange={cambiar} className="mt-1 w-full rounded-lg border p-2" /></label>}</section>
    <section className="rounded-xl border p-3 sm:p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between mb-3"><h2 className="font-semibold">Renglones</h2><button type="button" onClick={() => setRenglones((x) => [...x, lineaInicial()])} className="w-full sm:w-auto rounded-lg border px-3 py-2 text-sm inline-flex justify-center gap-1"><Plus size={16} /> Añadir renglón</button></div><div className="space-y-3 lg:hidden">{renglones.map((r, i) => <div key={i} className="rounded-lg bg-slate-50 p-3 grid grid-cols-1 sm:grid-cols-2 gap-2"><input placeholder="Artículo o descripción" value={r.descripcion} onChange={(e) => cambiarLinea(i, 'descripcion', e.target.value)} className="rounded border p-2 sm:col-span-2" /><DecimalInput value={r.cantidad} onChange={(v) => cambiarLinea(i, 'cantidad', v)} className="rounded border p-2" /><DecimalInput value={r.precio_unitario} onChange={(v) => cambiarLinea(i, 'precio_unitario', v)} className="rounded border p-2" />{r.ultimo_precio && Math.abs(numero(r.precio_unitario) / numero(r.ultimo_precio) - 1) > .15 && <p className="text-amber-700 text-xs sm:col-span-2"><AlertTriangle className="inline" size={13} /> Variación de precio superior a 15%.</p>}<button type="button" disabled={renglones.length === 1} onClick={() => setRenglones((x) => x.filter((_, n) => n !== i))} className="text-red-600 text-sm">Eliminar</button></div>)}</div><TablaScroll className="hidden lg:block"><table className="min-w-[800px] w-full text-sm"><thead><tr><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Descuento</th><th>Total</th><th /></tr></thead><tbody>{renglones.map((r, i) => <tr key={i}><td><input value={r.descripcion} onChange={(e) => cambiarLinea(i, 'descripcion', e.target.value)} className="w-full rounded border p-2" /></td><td><DecimalInput value={r.cantidad} onChange={(v) => cambiarLinea(i, 'cantidad', v)} className="w-24 rounded border p-2" /></td><td><DecimalInput value={r.precio_unitario} onChange={(v) => cambiarLinea(i, 'precio_unitario', v)} className="w-28 rounded border p-2" /></td><td><DecimalInput value={r.descuento} onChange={(v) => cambiarLinea(i, 'descuento', v)} className="w-24 rounded border p-2" /></td><td>{(numero(r.cantidad) * numero(r.precio_unitario) - numero(r.descuento)).toFixed(2)}</td><td><button type="button" onClick={() => setRenglones((x) => x.filter((_, n) => n !== i))} className="text-red-600"><Trash2 size={16} /></button></td></tr>)}</tbody></table></TablaScroll></section>
    <section className="rounded-xl border p-3 sm:p-5 space-y-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="fiscal_activo" checked={datos.fiscal_activo} onChange={cambiar} /> Aplicar datos fiscales</label>{datos.fiscal_activo && <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3"><label className="text-sm">IVA (%)<DecimalInput value={datos.porcentaje_iva} onChange={(v) => setDatos((x) => ({ ...x, porcentaje_iva: v }))} className="mt-1 w-full rounded border p-2" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="retiene_iva" checked={datos.retiene_iva} onChange={cambiar} /> Retención IVA</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="retiene_islr" checked={datos.retiene_islr} onChange={cambiar} /> Retención ISLR</label></div>}<p className="text-sm">Subtotal: <b>{subtotal.toFixed(2)} {datos.moneda}</b> · IVA: <b>{iva.toFixed(2)}</b> · Total: <b>{total.toFixed(2)}</b>{datos.tasa_aplicada && <> · Equivalente: <b>{equivalente.toFixed(2)} {datos.moneda === 'VES' ? 'USD' : 'VES'}</b></>}</p></section>
    <SubirComprobantes archivos={archivos} onChange={setArchivos} /><div className="fixed bottom-0 left-0 right-0 z-20 border-t bg-white p-3 sm:static sm:border-0 sm:p-0"><button disabled={guardando} className="w-full sm:w-auto sm:float-right rounded-lg px-4 py-3 text-white disabled:opacity-50" style={{ background: 'var(--pb)' }}>{guardando ? 'Guardando…' : 'Registrar egreso de contado'}</button></div><ProveedorRapidoModal open={modalProveedor} onClose={() => setModalProveedor(false)} onGuardar={guardarProveedor} /></form>;
}
