# Generated by Django 6.0.4 on 2026-09-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0010_empleado_tipo_contrato'),
        ('secretaria', '0028_alumno_cedula_alumno_cedula_nacionalidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFirmante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=15)),
                ('nacionalidad', models.CharField(choices=[('V', 'V'), ('E', 'E')], default='V', max_length=1)),
                ('cargo', models.CharField(max_length=150)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='constancias/firmas/')),
                ('sello_imagen', models.ImageField(blank=True, null=True, upload_to='constancias/sellos/')),
                ('estampado_global_activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_firmante_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Firmante',
                'verbose_name_plural': 'Configuración del Firmante',
            },
        ),
        migrations.CreateModel(
            name='PlantillaConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estudio', 'Estudio'), ('conducta', 'Buena Conducta'), ('retiro', 'Retiro'), ('trabajo', 'Trabajo')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('destinatario', models.CharField(choices=[('alumno', 'Alumno'), ('trabajador', 'Trabajador')], max_length=15)),
                ('cuerpo_html', models.TextField()),
                ('anexo_html', models.TextField(blank=True, default='')),
                ('anexo_habilitado', models.BooleanField(default=False)),
                ('permite_estampado', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_constancia_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Constancia',
                'verbose_name_plural': 'Plantillas de Constancia',
            },
        ),
        migrations.CreateModel(
            name='ConstanciaEmitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('estudio', 'Estudio'), ('conducta', 'Buena Conducta'), ('retiro', 'Retiro'), ('trabajo', 'Trabajo')], max_length=20)),
                ('html_renderizado', models.TextField()),
                ('datos_capturados', models.JSONField(blank=True, default=dict)),
                ('salio_firmada', models.BooleanField(default=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='secretaria.alumno')),
                ('emitida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomina.empleado')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constancias.plantillaconstancia')),
            ],
            options={
                'verbose_name': 'Constancia Emitida',
                'verbose_name_plural': 'Constancias Emitidas',
                'indexes': [models.Index(fields=['tipo', 'periodo_escolar'], name='constancias_tipo_260964_idx')],
            },
        ),
    ]
