from django.urls import path
from .views import (
    DocentesView,
    DocenteDetailView,
    DocenteAsignarMateriasView,
    HistorialNotaView,
    MateriasView,
    MateriaDetailView,
    LapsosView,
    LapsoDetailView,
    NotasGradoView,
    AsistenciaView,
    ResumenAsistenciaView,
    HorariosView,
    HorarioDetailView,
    BoletinView,
    GenerarHorarioView,
    IncidentesListCreateView,
    IncidenteDetailView,
    DocenteMisMateriasView,
    DocenteMiHorarioView,
    DocenteProximasEvaluacionesView,
    AlertasRiesgoDocenteView,
    RadarCierreLapsoView,
    ComparacionMateriaView,
    DocenteMiPerfilView,
    DocenteFotoPerfilView,
    EventosCalendarioView,
    EventoCalendarioDetailView,
    MaterialEstudioListCreateView,
    MaterialEstudioDetailView,
    RendimientoAlumnoView,
    RendimientoSeccionView,
    AlertasRendimientoView,
    PlanEvaluacionView,
    PlanEvaluacionNotasView,
)

urlpatterns = [
    path('materias/',              MateriasView.as_view()),
    path('materias/<int:pk>/',     MateriaDetailView.as_view()),
    path('docentes/',              DocentesView.as_view()),
    path('docentes/<int:pk>/',     DocenteDetailView.as_view()),
    path('docentes/<int:pk>/asignar-materias/', DocenteAsignarMateriasView.as_view()),
    path('lapsos/',                LapsosView.as_view()),
    path('lapsos/<int:pk>/',       LapsoDetailView.as_view()),
    path('notas/',                 NotasGradoView.as_view()),
    path('asistencia/',            AsistenciaView.as_view()),
    path('asistencia/resumen/',    ResumenAsistenciaView.as_view()),
    path('horarios/',              HorariosView.as_view()),
    path('horarios/<int:pk>/',     HorarioDetailView.as_view()),
    path('horarios/generar/',      GenerarHorarioView.as_view()),
    path('boletin/',               BoletinView.as_view()),
    path('notas/<int:nota_id>/historial/', HistorialNotaView.as_view()),
    path('incidentes/',            IncidentesListCreateView.as_view()),
    path('incidentes/<int:pk>/',   IncidenteDetailView.as_view()),
    path('docente/mis-materias/',  DocenteMisMateriasView.as_view()),
    path('docente/mi-horario/',    DocenteMiHorarioView.as_view()),
    path('docente/proximas-evaluaciones/', DocenteProximasEvaluacionesView.as_view()),
    path('docente/alertas-riesgo/', AlertasRiesgoDocenteView.as_view()),
    path('docente/radar-cierre-lapso/', RadarCierreLapsoView.as_view()),
    path('docente/comparacion-materia/<int:materia_id>/', ComparacionMateriaView.as_view()),
    path('docente/mi-perfil/',       DocenteMiPerfilView.as_view()),
    path('docente/mi-perfil/foto/',  DocenteFotoPerfilView.as_view()),
    path('eventos-calendario/',        EventosCalendarioView.as_view()),
    path('eventos-calendario/<int:pk>/', EventoCalendarioDetailView.as_view()),
    path('materiales/',            MaterialEstudioListCreateView.as_view()),
    path('materiales/<int:pk>/',   MaterialEstudioDetailView.as_view()),
    path('rendimiento/alumno/<int:alumno_id>/',        RendimientoAlumnoView.as_view()),
    path('rendimiento/seccion/<str:grado_seccion>/',   RendimientoSeccionView.as_view()),
    path('rendimiento/alertas/',                       AlertasRendimientoView.as_view()),
    path('docente/plan-evaluacion/',                    PlanEvaluacionView.as_view()),
    path('docente/plan-evaluacion/notas/',              PlanEvaluacionNotasView.as_view()),
]
