import { useState } from 'react';
import { toast } from 'react-toastify';
import { Modal } from '../ui/Modal';
import DatePickerES from '../DatePickerES';
import DecimalInput from '../DecimalInput';
import { acuerdoCuotas, anularCuenta, aplazarCuenta, confirmarMonto, posponerRecordatorio } from '../../services/cuentasPagarService';
import { parseApiError } from '../../utils/apiError';
const hoy = new Date().toISOString().slice(0, 10);
export function AccionCuentaModal({ tipo, cuenta, open, onClose, onHecho }) {
 const [fecha, setFecha] = useState(hoy); const [motivo, setMotivo] = useState(''); const [monto, setMonto] = useState(cuenta?.monto_documento || ''); const [tasa, setTasa] = useState(cuenta?.tasa_aplicada || ''); const [cuotas, setCuotas] = useState([{ fecha_vencimiento: hoy, monto: cuenta?.saldo || '' }]); const [guardando, setGuardando] = useState(false);
 if (!cuenta) return null; const titulo = { aplazar: 'Aplazar vencimiento', posponer: 'Posponer recordatorio', cuotas: 'Acuerdo de cuotas', confirmar: 'Confirmar monto', anular: 'Anular cuenta' }[tipo];
 const guardar = async (e) => { e.preventDefault(); if ((tipo === 'aplazar' || tipo === 'posponer' || tipo === 'anular') && !motivo.trim()) return toast.error('El motivo es obligatorio.'); if (tipo === 'cuotas' && Math.abs(cuotas.reduce((s, c) => s + Number(c.monto || 0), 0) - Number(cuenta.saldo)) > .01) return toast.error('La suma de las cuotas debe cuadrar con el saldo.'); setGuardando(true); try { if (tipo === 'aplazar') await aplazarCuenta(cuenta.id, { fecha_nueva: fecha, motivo }); if (tipo === 'posponer') await posponerRecordatorio(cuenta.id, { hasta: fecha, motivo }); if (tipo === 'cuotas') await acuerdoCuotas(cuenta.id, { cuotas }); if (tipo === 'confirmar') await confirmarMonto(cuenta.id, { monto_documento: monto, tasa_aplicada: tasa }); if (tipo === 'anular') await anularCuenta(cuenta.id, { motivo }); toast.success('Cambio registrado.'); onHecho?.(); onClose(); } catch (error) { toast.error(parseApiError(error)); } finally { setGuardando(false); } };
 return <Modal open={open} onClose={onClose} titulo={titulo} footer={<><button type="button" onClick={onClose} className="px-4 py-2">Cancelar</button><button form="accion-cxp" disabled={guardando} className="rounded-lg px-4 py-2 text-white" style={{ background: tipo === 'anular' ? '#b91c1c' : 'var(--pb)' }}>{guardando ? 'Guardando…' : 'Confirmar'}</button></>}><form id="accion-cxp" onSubmit={guardar} className="space-y-4">{tipo === 'aplazar' && <p className="text-sm">Aplazada {cuenta.veces_aplazada || 0} veces.</p>}{['aplazar', 'posponer'].includes(tipo) && <label className="block text-sm">{tipo === 'aplazar' ? 'Nueva fecha de vencimiento' : 'Silenciar hasta'}<DatePickerES value={fecha} onChange={(e) => setFecha(e.target.value)} className="mt-1 w-full rounded border p-2" /></label>}{tipo === 'confirmar' && <><label className="block text-sm">Monto ({cuenta.moneda})<DecimalInput value={monto} onChange={setMonto} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Tasa BCV<DecimalInput value={tasa} onChange={setTasa} className="mt-1 w-full rounded border p-2" /></label></>}{tipo === 'cuotas' && <div className="space-y-2">{cuotas.map((c, i) => <div key={i} className="grid grid-cols-1 sm:grid-cols-2 gap-2"><DatePickerES value={c.fecha_vencimiento} onChange={(e) => setCuotas((x) => x.map((v, n) => n === i ? { ...v, fecha_vencimiento: e.target.value } : v))} className="rounded border p-2" /><DecimalInput value={c.monto} onChange={(v) => setCuotas((x) => x.map((q, n) => n === i ? { ...q, monto: v } : q))} className="rounded border p-2" /></div>)}<button type="button" onClick={() => setCuotas((x) => [...x, { fecha_vencimiento: fecha, monto: '' }])} className="rounded border px-3 py-2 text-sm">Añadir cuota</button></div>}{['aplazar', 'posponer', 'anular'].includes(tipo) && <label className="block text-sm">Motivo<textarea required value={motivo} onChange={(e) => setMotivo(e.target.value)} className="mt-1 w-full rounded border p-2" /></label>}</form></Modal>;
}
