/* eslint-disable react-hooks/set-state-in-effect -- actualización tras respuesta HTTP */
import { useCallback, useEffect, useMemo, useState } from 'react';
import { addDays, addMonths, endOfMonth, endOfWeek, format, isSameMonth, startOfMonth, startOfWeek } from 'date-fns';
import { es } from 'date-fns/locale';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { toast } from 'react-toastify';
import { obtenerCalendario } from '../services/cuentasPagarService';
import { PageHeader } from '../components/ui/PageHeader';

const color = { vencida: 'bg-red-100 text-red-800', vence_hoy: 'bg-orange-100 text-orange-800', por_vencer: 'bg-amber-100 text-amber-800', al_dia: 'bg-blue-100 text-blue-800' };
const clave = (fecha) => format(fecha, 'yyyy-MM-dd');
export default function CalendarioPagos() {
  const [mes, setMes] = useState(startOfMonth(new Date())); const [items, setItems] = useState([]); const [seleccion, setSeleccion] = useState(null);
  const desde = format(startOfWeek(mes, { weekStartsOn: 1 }), 'yyyy-MM-dd'); const hasta = format(endOfWeek(endOfMonth(mes), { weekStartsOn: 1 }), 'yyyy-MM-dd');
  const cargar = useCallback(async () => { try { const { data } = await obtenerCalendario({ desde, hasta }); setItems(data.results || data || []); } catch (error) { toast.error(error.response?.data?.detalle || 'No se pudo cargar el calendario.'); } }, [desde, hasta]);
  useEffect(() => { cargar(); }, [cargar]);
  const porFecha = useMemo(() => items.reduce((acumulado, item) => { const fecha = item.fecha_vencimiento || item.fecha || item.vencimiento; (acumulado[fecha] ||= []).push(item); return acumulado; }, {}), [items]);
  const dias = []; for (let dia = startOfWeek(mes, { weekStartsOn: 1 }); dia <= endOfWeek(endOfMonth(mes), { weekStartsOn: 1 }); dia = addDays(dia, 1)) dias.push(dia);
  const detalle = seleccion ? porFecha[seleccion] || [] : [];
  return <div className="space-y-5 animate-fadeIn"><PageHeader titulo="Calendario de pagos" descripcion="Vencimientos y cuotas pendientes organizados por fecha." acciones={<div className="flex items-center justify-between gap-2 rounded-lg border border-slate-200 bg-white p-1"><button type="button" onClick={() => setMes((valor) => addMonths(valor, -1))} className="rounded-lg p-1.5 hover:bg-slate-100"><ChevronLeft size={18} /></button><span className="px-2 py-1 text-sm capitalize">{format(mes, 'MMMM yyyy', { locale: es })}</span><button type="button" onClick={() => setMes((valor) => addMonths(valor, 1))} className="rounded-lg p-1.5 hover:bg-slate-100"><ChevronRight size={18} /></button></div>} />
    <section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="grid gap-2 md:hidden">{Object.entries(porFecha).sort(([a], [b]) => a.localeCompare(b)).map(([fecha, cuentas]) => <button type="button" key={fecha} onClick={() => setSeleccion(fecha)} className="rounded-lg border border-slate-200 p-3 text-left transition-colors hover:bg-slate-50"><p className="font-medium capitalize">{format(new Date(`${fecha}T12:00:00`), "EEEE d 'de' MMMM", { locale: es })}</p><p className="mt-1 text-xs text-slate-500">{cuentas.length} pago(s) · {cuentas.map((cuenta) => cuenta.numero || cuenta.concepto).join(', ')}</p></button>)}{items.length === 0 && <p className="p-5 text-center text-sm text-slate-500">No hay vencimientos durante este mes.</p>}</div><div className="hidden md:grid md:grid-cols-7 md:gap-px md:overflow-hidden md:rounded-lg md:border md:bg-slate-200">{['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'].map((dia) => <div key={dia} className="bg-slate-50 p-2 text-center text-xs font-medium text-slate-500">{dia}</div>)}{dias.map((dia) => { const fecha = clave(dia); const cuentas = porFecha[fecha] || []; return <button type="button" key={fecha} onClick={() => setSeleccion(fecha)} className={`min-h-28 bg-white p-2 text-left hover:bg-slate-50 ${!isSameMonth(dia, mes) ? 'text-slate-400' : ''}`}><p className="text-xs font-medium">{format(dia, 'd')}</p><div className="mt-1 space-y-1">{cuentas.slice(0, 3).map((cuenta) => <p key={cuenta.id || cuenta.numero} className={`truncate rounded px-1 py-0.5 text-[11px] ${color[cuenta.situacion] || 'bg-slate-100'}`}>{cuenta.numero || cuenta.concepto} · {cuenta.monto_documento || cuenta.monto}</p>)}{cuentas.length > 3 && <p className="text-[11px] text-slate-500">+{cuentas.length - 3} más</p>}</div></button>; })}</div></section>
    {seleccion && <section className="rounded-xl border bg-white p-4"><div className="flex justify-between gap-2"><h2 className="font-semibold">Pagos del {format(new Date(`${seleccion}T12:00:00`), "d 'de' MMMM", { locale: es })}</h2><button type="button" onClick={() => setSeleccion(null)} className="text-sm text-slate-600">Cerrar</button></div><div className="mt-3 space-y-2">{detalle.map((cuenta) => <div key={cuenta.id || cuenta.numero} className="rounded-lg border p-3 text-sm"><p className="font-medium">{cuenta.numero} · {cuenta.proveedor_nombre || cuenta.proveedor}</p><p className="text-slate-500">{cuenta.concepto} · {cuenta.monto_documento || cuenta.monto} {cuenta.moneda}</p></div>)}</div></section>}</div>;
}
