import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, RefreshCw } from 'lucide-react';
import { toast } from 'react-toastify';
import { PageHeader } from '../components/ui/PageHeader';
import CuentaCard from '../components/cuentasPagar/CuentaCard';
import CuentaTabla from '../components/cuentasPagar/CuentaTabla';
import PagoModal from '../components/cuentasPagar/PagoModal';
import { listarCuentas, pagarMultiple } from '../services/cuentasPagarService';
import { parseApiError } from '../utils/apiError';
export default function CuentasPorPagar() {
 const [cuentas, setCuentas] = useState([]); const [filtros, setFiltros] = useState({ q: '', estado: '', situacion: '', moneda: '' }); const [seleccionados, setSeleccionados] = useState([]); const [pago, setPago] = useState(null); const [cargando, setCargando] = useState(true);
 const cargar = useCallback(async () => { setCargando(true); try { const { data } = await listarCuentas(filtros); setCuentas(data.results || data || []); } catch (error) { toast.error(parseApiError(error)); } finally { setCargando(false); } }, [filtros]);
 useEffect(() => { const timer = setTimeout(cargar, 0); return () => clearTimeout(timer); }, [cargar]);
 const alternar = (id) => setSeleccionados((x) => x.includes(id) ? x.filter((v) => v !== id) : [...x, id]);
 const multiple = async () => { const cuentasElegidas = cuentas.filter((c) => seleccionados.includes(c.id)); if (!cuentasElegidas.length) return; if (new Set(cuentasElegidas.map((c) => c.proveedor)).size > 1) return toast.error('El pago múltiple requiere cuentas del mismo proveedor.'); try { await pagarMultiple({ pagos: cuentasElegidas.map((c) => ({ cuenta: c.id, monto_aplicado: c.saldo, moneda: c.moneda, tasa_aplicada: c.tasa_aplicada, fecha_pago: new Date().toISOString().slice(0, 10), monto_pagado: c.saldo, metodo_pago: 'transferencia' })) }); toast.success('Pagos múltiples registrados.'); setSeleccionados([]); cargar(); } catch (error) { toast.error(parseApiError(error)); } };
 const change = (e) => setFiltros((x) => ({ ...x, [e.target.name]: e.target.value }));
 return <div className="space-y-5 animate-fadeIn"><PageHeader titulo="Cuentas por pagar" descripcion="Deudas, abonos y vencimientos de proveedores" acciones={<Link to="/cuentas-por-pagar/nueva" className="w-full sm:w-auto inline-flex justify-center gap-2 rounded-lg px-4 py-2 text-white" style={{ background: 'var(--pb)' }}><Plus size={17} /> Nueva cuenta</Link>} /><section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-2"><input name="q" value={filtros.q} onChange={change} placeholder="Buscar cuenta o proveedor" className="rounded-lg border border-slate-300 bg-white p-2 text-sm" /><select name="estado" value={filtros.estado} onChange={change} className="rounded-lg border border-slate-300 bg-white p-2 text-sm"><option value="">Todos los estados</option><option value="pendiente">Pendientes</option><option value="parcial">Parciales</option><option value="pagada">Pagadas</option></select><select name="situacion" value={filtros.situacion} onChange={change} className="rounded-lg border border-slate-300 bg-white p-2 text-sm"><option value="">Toda situación</option><option value="vencida">Vencidas</option><option value="vence_hoy">Vencen hoy</option><option value="por_vencer">Por vencer</option></select><select name="moneda" value={filtros.moneda} onChange={change} className="rounded-lg border border-slate-300 bg-white p-2 text-sm"><option value="">USD y Bs</option><option>USD</option><option value="VES">Bs</option></select><button onClick={cargar} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium transition-colors hover:bg-slate-50"><RefreshCw className="inline" size={15} /> Actualizar</button></section>{seleccionados.length > 0 && <section className="sticky bottom-2 z-10 rounded-xl bg-slate-900 p-3 text-white flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><span>{seleccionados.length} cuenta(s) seleccionada(s)</span><button onClick={multiple} className="rounded bg-white px-3 py-2 text-sm text-slate-900">Registrar pago múltiple</button></section>}<section className="lg:hidden space-y-3">{cargando ? <p>Cargando cuentas…</p> : cuentas.length ? cuentas.map((c) => <CuentaCard key={c.id} cuenta={c} seleccionada={seleccionados.includes(c.id)} onSeleccionar={alternar} onPagar={setPago} />) : <p className="rounded-xl border p-8 text-center text-slate-500">No hay cuentas con estos filtros.</p>}</section><section className="hidden lg:block">{cargando ? <p>Cargando cuentas…</p> : <CuentaTabla cuentas={cuentas} seleccionados={seleccionados} onSeleccionar={alternar} onPagar={setPago} />}</section><PagoModal key={pago?.id ?? "cerrado"} cuenta={pago} open={Boolean(pago)} onClose={() => setPago(null)} onPago={cargar} /></div>;
}
