import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Ban, ChevronLeft } from 'lucide-react';
import { toast } from 'react-toastify';
import { PageHeader } from '../components/ui/PageHeader';
import { TablaScroll } from '../components/ui/TablaScroll';
import SubirComprobantes from '../components/egresos/SubirComprobantes';
import { anularEgreso, obtenerEgreso } from '../services/egresosService';
import { fmt, fmtFecha } from '../utils/format';
import { parseApiError } from '../utils/apiError';

export default function EgresoDetalle() { const { id } = useParams(); const [egreso, setEgreso] = useState(null); const [anulando, setAnulando] = useState(false); const cargar = useCallback(async () => { try { const { data } = await obtenerEgreso(id); setEgreso(data); } catch (error) { toast.error(parseApiError(error)); } }, [id]); useEffect(() => { cargar(); }, [cargar]); const anular = async () => { const motivo = window.prompt('Indica el motivo de anulación:'); if (!motivo?.trim()) return; setAnulando(true); try { await anularEgreso(id, motivo); toast.success('Egreso anulado.'); cargar(); } catch (error) { toast.error(parseApiError(error)); } finally { setAnulando(false); } }; if (!egreso) return <p className="p-6">Cargando egreso…</p>; const pagos = egreso.pagos_cuenta_por_pagar || []; return <div className="space-y-5"><PageHeader titulo={`Egreso ${egreso.numero_documento || `#${id}`}`} descripcion={`${egreso.proveedor_nombre || 'Proveedor'} · ${fmtFecha(egreso.fecha_egreso)}`} acciones={<Link to="/egresos" className="inline-flex gap-1 text-sm"><ChevronLeft size={16} /> Volver</Link>} /><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3"><div className="rounded-xl border p-4"><p className="text-xs">USD</p><b>$ {fmt(egreso.monto_usd, 2)}</b></div><div className="rounded-xl border p-4"><p className="text-xs">Bolívares</p><b>Bs. {fmt(egreso.monto_ves, 2)}</b></div><div className="rounded-xl border p-4"><p className="text-xs">Origen</p><b>{egreso.origen === 'cuenta_por_pagar' ? 'Cuenta por pagar liquidada' : 'Factura de contado'}</b></div></div>{pagos.length > 0 && <section><h2 className="mb-2 font-semibold">Histórico de abonos</h2><TablaScroll><table className="min-w-[680px] w-full text-sm"><thead><tr><th className="p-2 text-left">Fecha</th><th className="p-2 text-left">Método</th><th className="p-2 text-left">Tasa</th><th className="p-2 text-left">USD</th><th className="p-2 text-left">VES</th><th className="p-2 text-left">Referencia</th></tr></thead><tbody>{pagos.map((p, i) => <tr key={p.id || i} className="border-t"><td className="p-2">{fmtFecha(p.fecha_pago)}</td><td className="p-2">{p.metodo_pago}</td><td className="p-2">{fmt(p.tasa_aplicada, 2)}</td><td className="p-2">$ {fmt(p.monto_usd, 2)}</td><td className="p-2">Bs. {fmt(p.monto_ves, 2)}</td><td className="p-2">{p.referencia || '—'}</td></tr>)}</tbody></table></TablaScroll></section>}<SubirComprobantes archivos={egreso.comprobantes || []} onChange={() => {}} disabled />{egreso.estado !== 'anulado' && <button onClick={anular} disabled={anulando} className="w-full sm:w-auto rounded-lg border border-red-300 px-4 py-2 text-red-700 inline-flex justify-center gap-2"><Ban size={16} /> {anulando ? 'Anulando…' : 'Anular egreso'}</button>}</div>; }
