import { useCallback, useEffect, useState } from 'react';
import { Plus, Search } from 'lucide-react';
import { toast } from 'react-toastify';
import { PageHeader } from '../components/ui/PageHeader';
import { TablaScroll } from '../components/ui/TablaScroll';
import ProveedorRapidoModal from '../components/proveedores/ProveedorRapidoModal';
import SkeletonFila from '../components/egresos/SkeletonFila';
import { crearProveedor, listarProveedores } from '../services/finanzasService';
import { parseApiError } from '../utils/apiError';

export default function Proveedores() { const [items, setItems] = useState([]); const [q, setQ] = useState(''); const [cargando, setCargando] = useState(true); const [modal, setModal] = useState(false); const cargar = useCallback(async () => { setCargando(true); try { const { data } = await listarProveedores({ q, activo: true }); setItems(data.results || data); } catch (error) { toast.error(parseApiError(error)); } finally { setCargando(false); } }, [q]); useEffect(() => { const timer = setTimeout(cargar, 250); return () => clearTimeout(timer); }, [cargar]); const guardar = async (datos) => { try { const { data } = await crearProveedor(datos); setItems((x) => [data, ...x]); toast.success('Proveedor creado correctamente.'); } catch (error) { toast.error(parseApiError(error)); throw error; } }; return <div className="space-y-5"><PageHeader titulo="Proveedores" descripcion="Directorio de proveedores para egresos de contado" acciones={<button onClick={() => setModal(true)} className="w-full sm:w-auto inline-flex justify-center gap-2 rounded-lg px-4 py-2 text-white" style={{ background: 'var(--pb)' }}><Plus size={17} /> Nuevo proveedor</button>} /><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar por razón social o RIF" className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm" /></label></div><TablaScroll><table className="min-w-[640px] w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Razón social</th><th className="p-3 text-left">RIF</th><th className="p-3 text-left">Condición habitual</th><th className="p-3 text-left">Estado</th></tr></thead><tbody>{cargando ? [1, 2, 3].map((i) => <SkeletonFila key={i} />) : items.length === 0 ? <tr><td colSpan="4" className="p-8 text-center text-slate-500">No hay proveedores registrados.</td></tr> : items.map((p) => <tr className="border-t" key={p.id}><td className="p-3 font-medium">{p.razon_social}</td><td className="p-3">{p.rif}</td><td className="p-3 capitalize">{p.condicion_habitual || 'contado'}</td><td className="p-3">{p.activo === false ? 'Inactivo' : 'Activo'}</td></tr>)}</tbody></table></TablaScroll><ProveedorRapidoModal open={modal} onClose={() => setModal(false)} onGuardar={guardar} /></div>; }
