/* eslint-disable react-hooks/set-state-in-effect -- actualización tras respuesta HTTP */
import { useCallback, useEffect, useState } from 'react';
import { endOfMonth, format, startOfMonth } from 'date-fns';
import { FileSpreadsheet, FileText, RefreshCw } from 'lucide-react';
import { toast } from 'react-toastify';
import { obtenerReporte } from '../services/cuentasPagarService';
import DatePickerES from '../components/DatePickerES';
import { PageHeader } from '../components/ui/PageHeader';
import TablaInformeCxP from '../components/cuentasPagar/reportes/TablaInformeCxP';
import { descargarReporteCuentasPagarPDF } from '../utils/cuentasPagarPDF';
import { descargarReporteCuentasPagarExcel } from '../utils/cuentasPagarExcel';

const INFORMES = [['cuentas-pendientes-al-corte', 'Cuentas pendientes al corte'], ['antiguedad-saldos', 'Antigüedad de saldos'], ['pagos-realizados', 'Pagos realizados'], ['vencimientos', 'Vencimientos'], ['aplazamientos', 'Aplazamientos'], ['estado-cuenta-proveedor', 'Estado de cuenta por proveedor'], ['proyeccion-pagos', 'Proyección de pagos'], ['recurrentes', 'Recurrentes']];
const COLUMNAS = [{ key: 'numero', label: 'Número' }, { key: 'proveedor', label: 'Proveedor' }, { key: 'concepto', label: 'Concepto' }, { key: 'fecha_vencimiento', label: 'Vencimiento' }, { key: 'monto_usd', label: 'USD', tipo: 'numero' }, { key: 'monto_ves', label: 'Bs.', tipo: 'numero' }, { key: 'estado', label: 'Estado' }];
export default function ReportesCuentasPorPagar() {
  const hoy = new Date(); const [informe, setInforme] = useState(INFORMES[0][0]); const [filtros, setFiltros] = useState({ desde: format(startOfMonth(hoy), 'yyyy-MM-dd'), hasta: format(endOfMonth(hoy), 'yyyy-MM-dd'), moneda: 'original', proveedor: '', sede: '' }); const [filas, setFilas] = useState([]); const [cargando, setCargando] = useState(false);
  const cargar = useCallback(async () => { setCargando(true); try { const { data } = await obtenerReporte(informe, { ...filtros, proveedor: filtros.proveedor || undefined, sede: filtros.sede || undefined }); setFilas(data.resultados || data.results || data || []); } catch (error) { toast.error(error.response?.data?.detalle || 'No se pudo cargar el informe.'); } finally { setCargando(false); } }, [filtros, informe]);
  useEffect(() => { cargar(); }, [cargar]); const nombre = INFORMES.find(([id]) => id === informe)?.[1] || 'Informe'; const exportar = (tipo) => { const payload = { titulo: nombre, columnas: COLUMNAS, filas, filtros, usuario: 'Usuario actual' }; if (tipo === 'pdf') descargarReporteCuentasPagarPDF(payload); else descargarReporteCuentasPagarExcel(payload); };
  return <div className="space-y-5 animate-fadeIn"><PageHeader titulo="Informes de cuentas por pagar" descripcion="Informes de deuda, pagos, vencimientos y recurrencias." acciones={<div className="flex gap-2"><button disabled={!filas.length} onClick={() => exportar('pdf')} className="btn btn-secondary flex-1 sm:flex-none"><FileText size={16} /> PDF</button><button disabled={!filas.length} onClick={() => exportar('excel')} className="btn btn-primary flex-1 sm:flex-none"><FileSpreadsheet size={16} /> Excel</button></div>} /><section className="grid gap-2 rounded-xl border border-[var(--border)] p-3 sm:grid-cols-2 lg:grid-cols-5 bg-[var(--surface)]"><select value={informe} onChange={(evento) => setInforme(evento.target.value)} className="rounded-lg border border-[var(--border-md)] bg-[var(--surface)] p-2 text-sm font-normal normal-case tracking-normal text-[var(--jet)]">{INFORMES.map(([id, titulo]) => <option key={id} value={id}>{titulo}</option>)}</select><select value={filtros.moneda} onChange={(evento) => setFiltros((actual) => ({ ...actual, moneda: evento.target.value }))} className="rounded-lg border border-[var(--border-md)] bg-[var(--surface)] p-2 text-sm font-normal normal-case tracking-normal text-[var(--jet)]"><option value="original">Original / ambas</option><option value="USD">USD</option><option value="VES">Bolívares</option></select><DatePickerES value={filtros.desde} onChange={(evento) => setFiltros((actual) => ({ ...actual, desde: evento.target.value }))} className="input" placeholder="Desde" /><DatePickerES value={filtros.hasta} onChange={(evento) => setFiltros((actual) => ({ ...actual, hasta: evento.target.value }))} className="input" placeholder="Hasta" /><button type="button" onClick={cargar} className="btn btn-secondary"><RefreshCw size={16} /> Actualizar</button><input value={filtros.proveedor} onChange={(evento) => setFiltros((actual) => ({ ...actual, proveedor: evento.target.value }))} className="rounded-lg border border-[var(--border-md)] bg-[var(--surface)] p-2 text-sm font-normal normal-case tracking-normal text-[var(--jet)]" placeholder="Proveedor / ID" /><input value={filtros.sede} onChange={(evento) => setFiltros((actual) => ({ ...actual, sede: evento.target.value }))} className="rounded-lg border border-[var(--border-md)] bg-[var(--surface)] p-2 text-sm font-normal normal-case tracking-normal text-[var(--jet)]" placeholder="Sede / ID" /></section><section className="overflow-hidden rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)]"><div className="border-b px-4 py-3"><h2 className="font-semibold">{nombre}</h2><p className="mt-1 text-xs text-[var(--ash)]">Rango: {filtros.desde} al {filtros.hasta} · Moneda: {filtros.moneda}</p></div><TablaInformeCxP columnas={COLUMNAS} filas={filas} cargando={cargando} /></section></div>;
}
