import { useCallback, useEffect, useState } from 'react';
import { BadgeDollarSign, FileWarning, Landmark, RefreshCw, WalletCards } from 'lucide-react';
import { toast } from 'react-toastify';
import { Link } from 'react-router-dom';
import apiClient from '../api/apiClient';
import DatePickerES from '../components/DatePickerES';
import { PageHeader } from '../components/ui/PageHeader';
import DatoResumen from '../components/egresos/DatoResumen';
import SelectorSede from '../components/egresos/SelectorSede';
import MenuNuevoEgreso from '../components/egresos/MenuNuevoEgreso';

// Tarjeta del resumen que lleva a la lista o informe correspondiente.
function Enlace({ to, children }) {
  return <Link to={to} className="block rounded-[var(--radius-card)] transition-shadow hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--pb)]">{children}</Link>;
}

const dinero = (valor, moneda) => `${moneda === 'VES' ? 'Bs.' : '$'} ${Number(valor || 0).toLocaleString('es-VE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const porcentaje = (actual) => `${Number(actual || 0) >= 0 ? '+' : ''}${Number(actual || 0).toFixed(1)}%`;
const vacio = { pagado_mes: {}, mes_previo: {}, variacion: {}, comprometido_pendiente: {}, faltantes_comprobante: 0, top_categorias: [], top_proveedores: [], presupuesto_consumido: [], alertas_presupuesto: [] };

function Barras({ titulo, filas, etiqueta }) {
  const maximo = Math.max(...filas.map((fila) => Number(fila.monto_usd || 0)), 1);
  return <section className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-semibold text-[var(--jet)]">{titulo}</h2><div className="mt-4 space-y-3">{filas.length === 0 ? <p className="text-sm text-[var(--ash)]">Sin movimientos en el período.</p> : filas.map((fila, indice) => <div key={fila.categoria_id || fila.proveedor_id || indice}><div className="flex justify-between gap-2 text-xs"><span className="truncate">{fila[etiqueta] || 'Sin asignar'}</span><span className="font-medium tabular-nums text-[var(--jet)]">{dinero(fila.monto_usd, 'USD')}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-[var(--surface-sunken)]"><div className="h-full rounded-full bg-[var(--pb)]" style={{ width: `${Math.max(4, Number(fila.monto_usd || 0) * 100 / maximo)}%` }} /></div></div>)}</div></section>;
}

export default function TableroEgresos() {
  const [filtros, setFiltros] = useState({ desde: '', hasta: '', sede: '' }); const [datos, setDatos] = useState(vacio); const [cargando, setCargando] = useState(true);
  const cargar = useCallback(async () => { setCargando(true); try { const { data } = await apiClient.get('egresos/tablero/', { params: { desde: filtros.desde || undefined, hasta: filtros.hasta || undefined, sede: filtros.sede || undefined } }); setDatos({ ...vacio, ...data }); } catch (error) { toast.error(error.response?.data?.detalle || 'No se pudo cargar el tablero de egresos.'); } finally { setCargando(false); } }, [filtros]);
  useEffect(() => { const temporizador = setTimeout(cargar, 0); return () => clearTimeout(temporizador); }, [cargar]);
  const consumido = datos.presupuesto_consumido.reduce((acumulado, fila) => acumulado + Number(fila.porcentaje_usd || fila.porcentaje_ves || 0), 0) / Math.max(datos.presupuesto_consumido.length, 1);
  return <div className="space-y-5 animate-fadeIn"><PageHeader titulo="Resumen de egresos" descripcion="Qué se ha pagado, qué falta por soportar y cómo va el presupuesto." acciones={<div className="flex flex-col gap-2 sm:flex-row"><button onClick={cargar} className="btn btn-secondary w-full sm:w-auto"><RefreshCw size={16} className={cargando ? 'animate-spin' : ''} /> Actualizar</button><MenuNuevoEgreso /></div>} />
    <div className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-3 grid grid-cols-1 sm:grid-cols-3 gap-2"><DatePickerES value={filtros.desde} onChange={(e) => setFiltros((actual) => ({ ...actual, desde: e.target.value }))} className="input" placeholder="Desde" /><DatePickerES value={filtros.hasta} onChange={(e) => setFiltros((actual) => ({ ...actual, hasta: e.target.value }))} className="input" placeholder="Hasta" /><SelectorSede value={filtros.sede} onChange={(sede) => setFiltros((actual) => ({ ...actual, sede }))} /></div>
    {cargando ? <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-busy="true">{[1, 2, 3, 4].map((i) => <div key={i} className="h-[104px] animate-pulse rounded-[var(--radius-card)] bg-[var(--surface-sunken)]" />)}</div> : <><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><Enlace to={`/egresos/movimientos?${new URLSearchParams({ ...(filtros.desde && { desde: filtros.desde }), ...(filtros.hasta && { hasta: filtros.hasta }) })}`}><DatoResumen className="h-full" icono={WalletCards} etiqueta="Pagado este período" valor={dinero(datos.pagado_mes.monto_usd, 'USD')} detalle={dinero(datos.pagado_mes.monto_ves, 'VES')} /></Enlace><DatoResumen icono={BadgeDollarSign} etiqueta="Variación vs. período anterior" valor={porcentaje(datos.variacion.usd)} detalle={`USD · Bs. ${porcentaje(datos.variacion.ves)}`} alerta={Number(datos.variacion.usd) > 15} /><Enlace to="/egresos/reportes?informe=ejecucion-presupuestaria"><DatoResumen className="h-full" icono={Landmark} etiqueta="Presupuesto consumido" valor={`${consumido.toFixed(1)}%`} detalle={`${datos.presupuesto_consumido.length} categorías presupuestadas`} alerta={consumido >= 80} /></Enlace><Enlace to="/egresos/movimientos?sin_comprobante=1"><DatoResumen className="h-full" icono={FileWarning} etiqueta="Sin comprobante" valor={datos.faltantes_comprobante} detalle="Toca para ver cuáles son" alerta={datos.faltantes_comprobante > 0} /></Enlace></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Barras titulo="Top 5 categorías" filas={datos.top_categorias} etiqueta="categoria__nombre" /><Barras titulo="Top 5 proveedores" filas={datos.top_proveedores} etiqueta="proveedor__razon_social" /></div>
      <section className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Alertas de presupuesto</h2><span className="text-xs text-[var(--ash)]">80%: atención · 100%: excedido</span></div><div className="mt-3 grid gap-2">{datos.alertas_presupuesto.length === 0 ? <p className="text-sm text-[var(--ash)]">No hay categorías en nivel de alerta.</p> : datos.alertas_presupuesto.map((fila, indice) => { const pct = Number(fila.porcentaje_usd || fila.porcentaje_ves || 0); return <div key={`${fila.categoria_id}-${indice}`} className="rounded-[10px] border border-[var(--border)] p-3"><div className="flex justify-between gap-3 text-sm"><span>{fila.categoria}</span><span className={`font-semibold tabular-nums ${pct >= 100 ? 'text-[var(--red)]' : 'text-[var(--yellow)]'}`}>{pct.toFixed(1)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--surface-sunken)]"><div className={pct >= 100 ? 'h-full rounded-full bg-[var(--red)]' : 'h-full rounded-full bg-[var(--yellow)]'} style={{ width: `${Math.min(100, pct)}%` }} /></div><p className="mt-1 text-xs text-[var(--ash)]">Presupuesto {dinero(fila.presupuesto, fila.moneda_presupuesto)} · ejecutado {dinero(fila.moneda_presupuesto === 'VES' ? fila.pagado_ves : fila.pagado_usd, fila.moneda_presupuesto)}</p></div>; })}</div></section>
      <p className="text-xs text-[var(--ash)]">Comprometido pendiente: {dinero(datos.comprometido_pendiente.monto_usd, 'USD')} · {dinero(datos.comprometido_pendiente.monto_ves, 'VES')}. El acceso y los datos se restringen a administrador/director por la API.</p></>}</div>;
}
