import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CalendarClock, CircleDollarSign, RefreshCw } from 'lucide-react';
import { toast } from 'react-toastify';
import apiClient from '../api/apiClient';
import { PageHeader } from '../components/ui/PageHeader';
import ProyeccionSemanalCxP from '../components/cuentasPagar/tablero/ProyeccionSemanalCxP';

const vacio = { vencidas: {}, vence_hoy: {}, proximos_7_dias: {}, proximos_30_dias: {}, total_adeudado: {}, pagado_mes: {}, aplazadas_mes: {}, semana: [], proyeccion: [] };
const dinero = (valor, moneda) => `${moneda === 'VES' ? 'Bs.' : '$'} ${Number(valor || 0).toLocaleString('es-VE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const leer = (origen, clave) => origen?.[clave] ?? origen?.[clave === 'USD' ? 'monto_usd' : 'monto_ves'] ?? 0;
function Tarjeta({ titulo, datos, color, icono: Icono }) { return <article className={`rounded-xl border p-4 ${color}`}><div className="flex justify-between gap-3"><div><p className="text-xs font-medium text-slate-600">{titulo}</p><p className="mt-2 text-lg font-semibold tabular-nums">{datos?.cantidad ?? datos?.count ?? 0}</p><p className="mt-1 text-xs tabular-nums">{dinero(leer(datos, 'USD'), 'USD')} · {dinero(leer(datos, 'VES'), 'VES')}</p></div><Icono size={20} /></div></article>; }
export default function TableroCuentasPorPagar() {
  const [datos, setDatos] = useState(vacio); const [cargando, setCargando] = useState(true);
  const cargar = useCallback(async () => { setCargando(true); try { const [{ data }, proyeccion] = await Promise.all([apiClient.get('cuentas-por-pagar/tablero/'), apiClient.get('cuentas-por-pagar/proyeccion/')]); setDatos({ ...vacio, ...data, proyeccion: proyeccion.data?.results || proyeccion.data || data.proyeccion || [] }); } catch (error) { toast.error(error.response?.data?.detalle || 'No se pudo cargar el tablero de cuentas por pagar.'); } finally { setCargando(false); } }, []);
  useEffect(() => { cargar(); }, [cargar]);
  const semana = datos.semana || datos.cuentas_semana || [];
  return <div className="space-y-5 animate-fadeIn"><PageHeader titulo="Tablero de cuentas por pagar" descripcion="Vencimientos, deuda pendiente y flujo proyectado en USD y bolívares." acciones={<button type="button" onClick={cargar} className="inline-flex w-full items-center justify-center gap-2 rounded-lg border px-3 py-2 text-sm sm:w-auto"><RefreshCw size={16} /> Actualizar</button>} />
    {cargando ? <div className="rounded-xl border p-8 text-center text-sm text-slate-500">Actualizando indicadores…</div> : <><div className="grid grid-cols-2 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Tarjeta titulo="Vencidas" datos={datos.vencidas} color="border-red-200 bg-red-50 text-red-800" icono={AlertTriangle} /><Tarjeta titulo="Vencen hoy" datos={datos.vence_hoy} color="border-orange-200 bg-orange-50 text-orange-800" icono={CalendarClock} /><Tarjeta titulo="Próximos 7 días" datos={datos.proximos_7_dias} color="border-amber-200 bg-amber-50 text-amber-800" icono={CalendarClock} /><Tarjeta titulo="Próximos 30 días" datos={datos.proximos_30_dias} color="border-blue-200 bg-blue-50 text-blue-800" icono={CircleDollarSign} /></div>
      <div className="grid gap-3 sm:grid-cols-3"><Tarjeta titulo="Total adeudado" datos={datos.total_adeudado} color="bg-white" icono={CircleDollarSign} /><Tarjeta titulo="Pagado este mes" datos={datos.pagado_mes} color="bg-white" icono={CircleDollarSign} /><Tarjeta titulo="Aplazadas este mes" datos={datos.aplazadas_mes} color="bg-white" icono={CalendarClock} /></div>
      <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Lo que hay que pagar esta semana</h2><div className="mt-3 space-y-2">{semana.length === 0 ? <p className="text-sm text-slate-500">No hay cuentas pendientes esta semana.</p> : semana.map((cuenta) => <div key={cuenta.id} className="flex flex-col gap-1 rounded-lg border p-3 text-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{cuenta.numero} · {cuenta.proveedor_nombre || cuenta.proveedor}</p><p className="text-xs text-slate-500">{cuenta.concepto} · vence {cuenta.fecha_vencimiento}</p></div><div className="text-right"><p className="font-medium">{dinero(cuenta.monto_usd, 'USD')}</p><p className="text-xs text-slate-500">{dinero(cuenta.monto_ves, 'VES')} · {cuenta.prioridad}</p></div></div>)}</div></section><ProyeccionSemanalCxP filas={datos.proyeccion} /></>}</div>;
}
