import { useCallback, useEffect, useState } from 'react';
import { BadgeDollarSign, FileWarning, Landmark, RefreshCw, WalletCards } from 'lucide-react';
import { toast } from 'react-toastify';
import apiClient from '../api/apiClient';
import DatePickerES from '../components/DatePickerES';
import { PageHeader } from '../components/ui/PageHeader';

const dinero = (valor, moneda) => `${moneda === 'VES' ? 'Bs.' : '$'} ${Number(valor || 0).toLocaleString('es-VE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const porcentaje = (actual) => `${Number(actual || 0) >= 0 ? '+' : ''}${Number(actual || 0).toFixed(1)}%`;
const vacio = { pagado_mes: {}, mes_previo: {}, variacion: {}, comprometido_pendiente: {}, faltantes_comprobante: 0, top_categorias: [], top_proveedores: [], presupuesto_consumido: [], alertas_presupuesto: [] };

function Tarjeta({ icono: Icono, etiqueta, valor, detalle, alerta }) {
  return <article className={`rounded-xl border p-4 ${alerta ? 'border-[var(--yellow)] bg-[var(--yellow-light)]' : 'border-[var(--border)] bg-[var(--surface)]'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-[var(--ash)]">{etiqueta}</p><p className="mt-1 text-xl font-semibold tabular-nums sm:text-2xl">{valor}</p>{detalle && <p className="mt-1 text-xs text-[var(--ash)]">{detalle}</p>}</div><Icono size={20} className={alerta ? 'text-[var(--yellow)]' : 'text-[var(--ash)]'} /></div></article>;
}
function Barras({ titulo, filas, etiqueta }) {
  const maximo = Math.max(...filas.map((fila) => Number(fila.monto_usd || 0)), 1);
  return <section className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-semibold text-[var(--jet)]">{titulo}</h2><div className="mt-4 space-y-3">{filas.length === 0 ? <p className="text-sm text-[var(--ash)]">Sin movimientos en el período.</p> : filas.map((fila, indice) => <div key={fila.categoria_id || fila.proveedor_id || indice}><div className="flex justify-between gap-2 text-xs"><span className="truncate">{fila[etiqueta] || 'Sin asignar'}</span><span>{dinero(fila.monto_usd, 'USD')}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-[var(--surface-sunken)]"><div className="h-full rounded-full bg-[var(--pb)]" style={{ width: `${Math.max(4, Number(fila.monto_usd || 0) * 100 / maximo)}%` }} /></div></div>)}</div></section>;
}

export default function TableroEgresos() {
  const [filtros, setFiltros] = useState({ desde: '', hasta: '', sede: '' }); const [datos, setDatos] = useState(vacio); const [cargando, setCargando] = useState(true);
  const cargar = useCallback(async () => { setCargando(true); try { const { data } = await apiClient.get('egresos/tablero/', { params: { desde: filtros.desde || undefined, hasta: filtros.hasta || undefined, sede: filtros.sede || undefined } }); setDatos({ ...vacio, ...data }); } catch (error) { toast.error(error.response?.data?.detalle || 'No se pudo cargar el tablero de egresos.'); } finally { setCargando(false); } }, [filtros]);
  useEffect(() => { const temporizador = setTimeout(cargar, 0); return () => clearTimeout(temporizador); }, [cargar]);
  const consumido = datos.presupuesto_consumido.reduce((acumulado, fila) => acumulado + Number(fila.porcentaje_usd || fila.porcentaje_ves || 0), 0) / Math.max(datos.presupuesto_consumido.length, 1);
  return <div className="space-y-5 animate-fadeIn"><PageHeader titulo="Tablero de egresos" descripcion="Resumen de pagos reales, compromisos y presupuesto por sede." acciones={<button onClick={cargar} className="btn btn-secondary w-full sm:w-auto"><RefreshCw size={16} /> Actualizar</button>} />
    <div className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-3 grid grid-cols-1 sm:grid-cols-3 gap-2"><DatePickerES value={filtros.desde} onChange={(e) => setFiltros((actual) => ({ ...actual, desde: e.target.value }))} className="w-full rounded-lg border p-2 text-sm" placeholder="Desde" /><DatePickerES value={filtros.hasta} onChange={(e) => setFiltros((actual) => ({ ...actual, hasta: e.target.value }))} className="w-full rounded-lg border p-2 text-sm" placeholder="Hasta" /><input value={filtros.sede} onChange={(e) => setFiltros((actual) => ({ ...actual, sede: e.target.value }))} inputMode="numeric" className="rounded-lg border p-2 text-sm" placeholder="ID de sede (todas)" /></div>
    {cargando ? <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-busy="true">{[1, 2, 3, 4].map((i) => <div key={i} className="h-24 animate-pulse rounded-xl bg-[var(--surface-sunken)]" />)}</div> : <><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><Tarjeta icono={WalletCards} etiqueta="Pagado este período" valor={dinero(datos.pagado_mes.monto_usd, 'USD')} detalle={dinero(datos.pagado_mes.monto_ves, 'VES')} /><Tarjeta icono={BadgeDollarSign} etiqueta="Variación vs. período anterior" valor={porcentaje(datos.variacion.usd)} detalle={`USD · Bs. ${porcentaje(datos.variacion.ves)}`} alerta={Number(datos.variacion.usd) > 15} /><Tarjeta icono={Landmark} etiqueta="Presupuesto consumido" valor={`${consumido.toFixed(1)}%`} detalle={`${datos.presupuesto_consumido.length} categorías presupuestadas`} alerta={consumido >= 80} /><Tarjeta icono={FileWarning} etiqueta="Sin comprobante" valor={datos.faltantes_comprobante} detalle="Egresos que requieren soporte" alerta={datos.faltantes_comprobante > 0} /></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Barras titulo="Top 5 categorías" filas={datos.top_categorias} etiqueta="categoria__nombre" /><Barras titulo="Top 5 proveedores" filas={datos.top_proveedores} etiqueta="proveedor__razon_social" /></div>
      <section className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Alertas de presupuesto</h2><span className="text-xs text-[var(--ash)]">80%: atención · 100%: excedido</span></div><div className="mt-3 grid gap-2">{datos.alertas_presupuesto.length === 0 ? <p className="text-sm text-[var(--ash)]">No hay categorías en nivel de alerta.</p> : datos.alertas_presupuesto.map((fila, indice) => { const pct = Number(fila.porcentaje_usd || fila.porcentaje_ves || 0); return <div key={`${fila.categoria_id}-${indice}`} className="rounded-lg border p-3"><div className="flex justify-between gap-3 text-sm"><span>{fila.categoria}</span><span className={pct >= 100 ? 'font-semibold text-[var(--red)]' : 'font-semibold text-[var(--yellow)]'}>{pct.toFixed(1)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--surface-sunken)]"><div className={pct >= 100 ? 'h-full bg-[var(--red-light)]0' : 'h-full bg-[var(--yellow-light)]0'} style={{ width: `${Math.min(100, pct)}%` }} /></div><p className="mt-1 text-xs text-[var(--ash)]">Presupuesto {dinero(fila.presupuesto, fila.moneda_presupuesto)} · ejecutado {dinero(fila.moneda_presupuesto === 'VES' ? fila.pagado_ves : fila.pagado_usd, fila.moneda_presupuesto)}</p></div>; })}</div></section>
      <p className="text-xs text-[var(--ash)]">Comprometido pendiente: {dinero(datos.comprometido_pendiente.monto_usd, 'USD')} · {dinero(datos.comprometido_pendiente.monto_ves, 'VES')}. El acceso y los datos se restringen a administrador/director por la API.</p></>}</div>;
}
