/* eslint-disable react-hooks/set-state-in-effect -- actualización tras respuesta HTTP */
import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CalendarClock, CircleDollarSign, RefreshCw } from 'lucide-react';
import { toast } from 'react-toastify';
import { obtenerTablero, obtenerProyeccion } from '../services/cuentasPagarService';
import { PageHeader } from '../components/ui/PageHeader';
import ProyeccionSemanalCxP from '../components/cuentasPagar/tablero/ProyeccionSemanalCxP';

const vacio = { vencidas: {}, vence_hoy: {}, proximos_7_dias: {}, proximos_30_dias: {}, total_adeudado: {}, pagado_mes: {}, aplazadas_mes: {}, semana: [], proyeccion: [] };
const dinero = (valor, moneda) => `${moneda === 'VES' ? 'Bs.' : '$'} ${Number(valor || 0).toLocaleString('es-VE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const leer = (origen, clave) => origen?.[clave] ?? origen?.[clave === 'USD' ? 'monto_usd' : 'monto_ves'] ?? 0;
function Tarjeta({ titulo, datos, color, icono: Icono }) { return <article className={`rounded-xl border p-4 ${color}`}><div className="flex justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-[var(--ash)]">{titulo}</p><p className="mt-2 text-xl font-semibold tabular-nums sm:text-2xl">{datos?.cantidad ?? datos?.count ?? 0}</p><p className="mt-1 text-xs tabular-nums">{dinero(leer(datos, 'USD'), 'USD')} · {dinero(leer(datos, 'VES'), 'VES')}</p></div><Icono size={20} /></div></article>; }
export default function TableroCuentasPorPagar() {
  const [datos, setDatos] = useState(vacio); const [cargando, setCargando] = useState(true);
  const cargar = useCallback(async () => { setCargando(true); try { const [{ data }, proyeccion] = await Promise.all([obtenerTablero(), obtenerProyeccion()]); setDatos({ ...vacio, ...data, proyeccion: proyeccion.data?.results || proyeccion.data || data.proyeccion || [] }); } catch (error) { toast.error(error.response?.data?.detalle || 'No se pudo cargar el tablero de cuentas por pagar.'); } finally { setCargando(false); } }, []);
  useEffect(() => { cargar(); }, [cargar]);
  const semana = datos.semana || datos.cuentas_semana || [];
  return <div className="space-y-5 animate-fadeIn"><PageHeader titulo="Tablero de cuentas por pagar" descripcion="Vencimientos, deuda pendiente y flujo proyectado en USD y bolívares." acciones={<button type="button" onClick={cargar} className="btn btn-secondary w-full sm:w-auto"><RefreshCw size={16} /> Actualizar</button>} />
    {cargando ? <div className="grid grid-cols-2 gap-3 lg:grid-cols-4" aria-busy="true">{[1, 2, 3, 4].map((i) => <div key={i} className="h-24 animate-pulse rounded-xl bg-[var(--surface-sunken)]" />)}</div> : <><div className="grid grid-cols-2 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Tarjeta titulo="Vencidas" datos={datos.vencidas} color="border-[var(--red)] bg-[var(--red-light)] text-[var(--red)]" icono={AlertTriangle} /><Tarjeta titulo="Vencen hoy" datos={datos.vence_hoy} color="border-[var(--yellow)] bg-[var(--yellow-light)] text-[var(--yellow)]" icono={CalendarClock} /><Tarjeta titulo="Próximos 7 días" datos={datos.proximos_7_dias} color="border-[var(--yellow)] bg-[var(--yellow-light)] text-[var(--yellow)]" icono={CalendarClock} /><Tarjeta titulo="Próximos 30 días" datos={datos.proximos_30_dias} color="border-[var(--pb-mid)] bg-[var(--pb-light)] text-[var(--pb-mid)]" icono={CircleDollarSign} /></div>
      <div className="grid gap-3 sm:grid-cols-3"><Tarjeta titulo="Total adeudado" datos={datos.total_adeudado} color="border-[var(--border)] bg-[var(--surface)]" icono={CircleDollarSign} /><Tarjeta titulo="Pagado este mes" datos={datos.pagado_mes} color="border-[var(--border)] bg-[var(--surface)]" icono={CircleDollarSign} /><Tarjeta titulo="Aplazadas este mes" datos={datos.aplazadas_mes} color="border-[var(--border)] bg-[var(--surface)]" icono={CalendarClock} /></div>
      <section className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-semibold text-[var(--jet)]">Lo que hay que pagar esta semana</h2><div className="mt-3 space-y-2">{semana.length === 0 ? <p className="text-sm text-[var(--ash)]">No hay cuentas pendientes esta semana.</p> : semana.map((cuenta) => <div key={cuenta.id} className="flex flex-col gap-1 rounded-lg border p-3 text-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{cuenta.numero} · {cuenta.proveedor_nombre || cuenta.proveedor}</p><p className="text-xs text-[var(--ash)]">{cuenta.concepto} · vence {cuenta.fecha_vencimiento}</p></div><div className="text-right"><p className="font-medium">{dinero(cuenta.monto_usd, 'USD')}</p><p className="text-xs text-[var(--ash)]">{dinero(cuenta.monto_ves, 'VES')} · {cuenta.prioridad}</p></div></div>)}</div></section><ProyeccionSemanalCxP filas={datos.proyeccion} /></>}</div>;
}
