# Generated by Django 6.0.5 on 2026-05-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('director', 'Director Institucional'), ('sistemas', 'Departamento de Sistemas'), ('administrador', 'Administrador General'), ('cajero', 'Cajero / Staff Administrativo')], default='cajero', max_length=20)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
