# Generated by Django 6.0.5 on 2026-06-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('directivo_red', 'Directivo de Red'), ('director', 'Director Institucional'), ('sistemas', 'Departamento de Sistemas'), ('administrador', 'Administrador General'), ('cajero', 'Cajero / Staff Administrativo'), ('secretaria', 'Secretaria'), ('cobranza', 'Cobranza')], default='cajero', max_length=20),
        ),
    ]
