# Generated by Django 6.0.5 on 2026-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('directivo_red', 'Directivo de Red'), ('director', 'Director Institucional'), ('sistemas', 'Departamento de Sistemas'), ('administrador', 'Administrador General'), ('cajero', 'Cajero / Staff Administrativo'), ('secretaria', 'Secretaria'), ('cobranza', 'Cobranza'), ('docente', 'Docente'), ('representante', 'Representante (Portal)')], default='cajero', max_length=20),
        ),
    ]
