# Generated by Django 6.0.5 on 2026-08-03 23:50

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_docente_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[authentication.models.validar_tamano_adjunto]),
        ),
    ]
