# Generated by Django 6.0.4 on 2026-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_perfilusuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('directivo_red', 'Directivo de Red'), ('director', 'Director Institucional'), ('sistemas', 'Departamento de Sistemas'), ('administrador', 'Administrador General'), ('cajero', 'Cajero / Staff Administrativo'), ('secretaria', 'Secretaria'), ('cobranza', 'Cobranza'), ('docente', 'Docente'), ('coordinador', 'Coordinador Académico'), ('representante', 'Representante (Portal)')], default='cajero', max_length=20),
        ),
    ]
