# Generated by Django 6.0.4 on 2026-07-20 17:13

from django.db import migrations, models


def copiar_config_a_perfil_cobranza(apps, schema_editor):
    """Copia la config SMTP existente (usada hoy por cobranza/mora) al nuevo
    perfil 'cobranza', para no perder lo ya configurado."""
    ConfiguracionNotificaciones = apps.get_model('notificaciones', 'ConfiguracionNotificaciones')
    PerfilEmailRemitente = apps.get_model('notificaciones', 'PerfilEmailRemitente')
    cfg = ConfiguracionNotificaciones.objects.filter(pk=1).first()
    if not cfg:
        return
    PerfilEmailRemitente.objects.update_or_create(
        area='cobranza',
        defaults=dict(
            email_activo=cfg.email_activo,
            email_host=cfg.email_host,
            email_port=cfg.email_port,
            email_use_tls=cfg.email_use_tls,
            email_host_user=cfg.email_host_user,
            email_host_password=cfg.email_host_password,
            email_from=cfg.email_from,
        ),
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_configuracionnotificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmailRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('cobranza', 'Cobranza'), ('control_estudios', 'Control de Estudios')], max_length=20, unique=True)),
                ('email_activo', models.BooleanField(default=False, verbose_name='Email activo')),
                ('email_host', models.CharField(blank=True, default='smtp.hostinger.com', max_length=200)),
                ('email_port', models.PositiveIntegerField(default=465)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200)),
                ('email_host_password', models.CharField(blank=True, default='', max_length=500)),
                ('email_from', models.CharField(blank=True, default='', help_text='Ej: Cobranza <cobranza@colegio.edu.ve>', max_length=200)),
            ],
            options={
                'verbose_name': 'Perfil de Email por Área',
                'verbose_name_plural': 'Perfiles de Email por Área',
            },
        ),
        migrations.AlterField(
            model_name='notificacionlog',
            name='tipo',
            field=models.CharField(choices=[('mora_dia_0', 'Aviso factura (Dia 0)'), ('mora_dia_5', 'Recordatorio (Dia 5)'), ('mora_dia_10', 'Segundo aviso (Dia 10)'), ('mora_dia_15', 'Alerta director (Dia 15)'), ('comprobante', 'Comprobante subido'), ('comprobante_inscripcion', 'Comprobante de inscripción'), ('bienvenida', 'Bienvenida portal'), ('pago_exitoso', 'Pago confirmado'), ('prueba', 'Mensaje de prueba'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.RunPython(copiar_config_a_perfil_cobranza, noop),
    ]
