# Generated by Django 6.0.4 on 2026-07-28 19:02

import django.db.models.deletion
import notificaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_perfilemailremitente_alter_notificacionlog_tipo'),
        ('portal', '0004_alter_comprobantepago_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionlog',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=10),
        ),
        migrations.CreateModel(
            name='SuscripcionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('tipos_activos', models.JSONField(default=notificaciones.models._tipos_push_default)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to='portal.representanteuser')),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
            },
        ),
    ]
