# Generated by Django 6.0.4 on 2026-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_cifrar_credenciales_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionlog',
            name='tipo',
            field=models.CharField(choices=[('mora_dia_0', 'Aviso factura (Dia 0)'), ('mora_dia_5', 'Recordatorio (Dia 5)'), ('mora_dia_10', 'Segundo aviso (Dia 10)'), ('mora_dia_15', 'Alerta director (Dia 15)'), ('comprobante', 'Comprobante subido'), ('comprobante_inscripcion', 'Comprobante de inscripción'), ('bienvenida', 'Bienvenida portal'), ('reset_password', 'Recuperación de contraseña'), ('pago_exitoso', 'Pago confirmado'), ('prueba', 'Mensaje de prueba'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
    ]
