# Generated by Django 6.0.4 on 2026-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0007_agregar_tipo_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificaciones',
            name='dias_alerta_director',
            field=models.PositiveIntegerField(default=15, verbose_name='Días — alerta al director'),
        ),
        migrations.AddField(
            model_name='configuracionnotificaciones',
            name='dias_recordatorio_1',
            field=models.PositiveIntegerField(default=5, verbose_name='Días — primer recordatorio'),
        ),
        migrations.AddField(
            model_name='configuracionnotificaciones',
            name='dias_recordatorio_2',
            field=models.PositiveIntegerField(default=10, verbose_name='Días — segundo aviso'),
        ),
    ]
