# Generated by Django 6.0.4 on 2026-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0009_cobro_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantillawhatsapp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
