# Generated by Django 6.0.4 on 2026-10-08 17:08

import django.db.models.deletion
import notificaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0010_plantillawhatsapp_id_bigauto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuscripcionPushUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, unique=True)),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                ("activa", models.BooleanField(default=True)),
                (
                    "tipos_activos",
                    models.JSONField(
                        default=notificaciones.models._tipos_push_usuario_default
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones_push",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción Push (usuario del panel)",
                "verbose_name_plural": "Suscripciones Push (usuarios del panel)",
            },
        ),
    ]
