# Generated by Django 6.0.5 on 2026-05-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_financiero', models.CharField(choices=[('solvente', 'Solvente'), ('mora', 'En Mora'), ('becado', 'Becado Total')], default='solvente', max_length=15)),
                ('dia_limite_pago', models.PositiveSmallIntegerField(default=5)),
                ('cedula_escolar', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('grado_seccion', models.CharField(max_length=50)),
                ('porcentaje_beca', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BienNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado_conservacion', models.CharField(choices=[('optimo', 'Óptimo'), ('regular', 'Regular'), ('deteriorado', 'Deteriorado'), ('desincorporado', 'Desincorporado')], default='optimo', max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('valor_estimado_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_adquisicion', models.DateField()),
            ],
            options={
                'verbose_name': 'Bien Nacional',
                'verbose_name_plural': 'Bienes Nacionales',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_seccion', models.CharField(max_length=50, unique=True)),
                ('cupos_maximos', models.PositiveIntegerField(default=30)),
                ('cupos_utilizados', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_escolar', models.CharField(default='2025-2026', max_length=20)),
                ('grado_seccion', models.CharField(max_length=50)),
                ('tipo_ingreso', models.CharField(choices=[('nuevo', 'Nuevo Ingreso'), ('regular', 'Estudiante Regular')], max_length=15)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('documentos_completos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
            ],
        ),
    ]
