# Generated by Django 6.0.5 on 2026-05-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='motivo_retiro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretaria.alumno'),
        ),
    ]
