# Generated by Django 6.0.5 on 2026-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_alumno_activo_alumno_fecha_retiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_inscripciones', models.DateField()),
                ('fecha_fin_inscripciones', models.DateField()),
                ('fecha_inicio_ano_escolar', models.DateField()),
                ('fecha_fin_ano_escolar', models.DateField()),
                ('periodo_escolar_activo', models.CharField(default='2025-2026', max_length=20)),
                ('dia_limite_pago', models.PositiveSmallIntegerField(default=5)),
                ('notificaciones_activas', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grado_seccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
