# Generated by Django 6.0.4 on 2026-07-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0008_configuracionsistema_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grado_seccion',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
