# Generated by Django 6.0.5 on 2026-07-07 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0009_alter_alumno_grado_seccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('alumno', 'periodo_escolar'), name='unica_inscripcion_por_periodo'),
        ),
    ]
