# Generated by Django 6.0.5 on 2026-07-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0010_inscripcion_unica_inscripcion_por_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alergico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='bautizado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado_nacimiento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/fotos/'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion_procedencia',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='alumno',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='pais_nacimiento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nro_solvencia',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='representante',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='representante',
            name='nivel_estudio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='representante',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor', 'Tutor'), ('otro', 'Otro')], default='', max_length=10),
        ),
    ]
