# Generated by Django 6.0.5 on 2026-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0011_alumno_alergico_alumno_bautizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
