# Generated by Django 6.0.5 on 2026-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0012_alumno_fecha_nacimiento_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
