# Generated by Django 6.0.5 on 2026-07-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0014_alumno_parentesco_por_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='contacto_emergencia_nombre',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='contacto_emergencia_parentesco',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='contacto_emergencia_telefono',
        ),
    ]
