# Generated by Django 6.0.5 on 2026-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0015_eliminar_contacto_emergencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo_avec',
            field=models.ImageField(blank=True, help_text='Logo de AVEC para recibos de pago', null=True, upload_to='configuracion/logos/'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo_colegio',
            field=models.ImageField(blank=True, help_text='Logo del colegio para recibos de pago', null=True, upload_to='configuracion/logos/'),
        ),
    ]
