# Generated by Django 6.0.4 on 2026-09-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0016_configuracionsistema_logo_avec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='descripcion_web',
            field=models.CharField(blank=True, default='', help_text='Meta descripción del sitio (SEO).', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon del colegio', null=True, upload_to='configuracion/favicons/'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='favicon_url',
            field=models.URLField(blank=True, default='', help_text='URL del favicon (externo)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='titulo_web',
            field=models.CharField(blank=True, default='', help_text='Título mostrado en la pestaña del navegador. Si está vacío, se usa nombre_colegio.', max_length=200),
        ),
    ]
