# Generated by Django 6.0.4 on 2026-09-02 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0017_configuracionsistema_descripcion_web_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('deportiva', 'Deportiva'), ('socioeconomica', 'Socioeconómica'), ('hermanos', 'Hermanos'), ('empleado', 'Hijo de Empleado'), ('otra', 'Otra')], default='academica', max_length=20)),
                ('porcentaje', models.PositiveIntegerField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('documento_adjunto', models.FileField(blank=True, help_text='Documento de respaldo opcional (ej. constancia, solicitud firmada).', null=True, upload_to='becas/documentos/')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('revocada', 'Revocada')], default='activa', max_length=10)),
                ('fecha_otorgamiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.TextField(blank=True, default='')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='secretaria.alumno')),
                ('otorgada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='becas_otorgadas', to=settings.AUTH_USER_MODEL)),
                ('revocada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='becas_revocadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_desde'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('alumno', 'periodo_escolar'), name='unica_beca_activa_por_alumno_periodo')],
            },
        ),
    ]
