# Generated by Django 6.0.4 on 2026-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0019_backfill_becas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='adelantos_requieren_usd',
            field=models.BooleanField(default=True, help_text='Si está activo, los adelantos de mensualidades futuras solo se aceptan en Zelle o Efectivo Divisas (USD).'),
        ),
    ]
