# Generated by Django 6.0.4 on 2026-09-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0023_remove_configuracionsistema_logo_avec'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='pie_pagina_personalizado',
            field=models.ImageField(blank=True, help_text='Banner PNG (2200x220px, fondo transparente opcional) que reemplaza el pie de página de dirección/contacto en recibos y boletines. Si está vacío, se usa el pie de página estructurado por defecto.', null=True, upload_to='configuracion/logos/'),
        ),
    ]
