# Generated by Django 6.0.4 on 2026-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0024_configuracionsistema_pie_pagina_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='convenio_nomina',
            field=models.CharField(choices=[('generico', 'Genérico'), ('avec_ve', 'Convenio AVEC (Venezuela)')], default='generico', help_text='Convenio de nómina docente aplicable. Determina si el cálculo de asignaciones usa el plugin AVEC o el genérico.', max_length=20),
        ),
    ]
