# Generated by Django 6.0.4 on 2026-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0026_datos_convenio_nomina_avec'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='abonos_parciales_requieren_usd',
            field=models.BooleanField(default=True, help_text='Si está activo, un abono parcial de mensualidad solo se acepta si TODAS las líneas de la transacción son en Zelle o Efectivo Divisas (USD).'),
        ),
    ]
