# Generated by Django 6.0.4 on 2026-09-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0027_configuracionsistema_abonos_parciales_requieren_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cedula_nacionalidad',
            field=models.CharField(blank=True, choices=[('V', 'V'), ('E', 'E')], default='V', max_length=1),
        ),
    ]
