# Generated by Django 6.0.4 on 2026-09-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0028_alumno_cedula_alumno_cedula_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongrado',
            name='aula_fija',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
