# Generated by Django 6.0.4 on 2026-09-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0029_configuraciongrado_aula_fija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='abonos_parciales_requieren_usd',
            field=models.BooleanField(default=True, help_text='Si está activo, un abono parcial de un ADELANTO de mensualidad (mes futuro) solo se acepta si TODAS las líneas de la transacción son en Zelle o Efectivo Divisas (USD). No aplica a mensualidades ya vencidas.'),
        ),
    ]
