# Generated by Django 6.0.4 on 2026-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0030_alter_configuracionsistema_abonos_parciales_requieren_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tolerancia_conciliacion_ves',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Tolerancia (Bs) de la conciliación bancaria. Si la diferencia la supera, la observación es obligatoria.', max_digits=12),
        ),
    ]
