# Generated by Django 6.0.5 on 2026-05-21 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('monto_sistema_ves', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('monto_declarado_ves', models.DecimalField(decimal_places=2, max_digits=20)),
                ('diferencia', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('validado_por_director', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.PositiveSmallIntegerField(default=2026)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['anio', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares')], max_length=20)),
                ('concepto', models.CharField(choices=[('mensualidad', 'Mensualidad Escolar'), ('inscripcion', 'Inscripción'), ('materiales', 'Materiales'), ('actividades', 'Actividades Extraescolares'), ('multa', 'Multa'), ('otro', 'Otro')], default='mensualidad', max_length=20)),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto captado en divisas', max_digits=10)),
                ('tasa_aplicada', models.DecimalField(decimal_places=2, help_text='Tasa BCV del momento de la transacción', max_digits=12)),
                ('monto_ves', models.DecimalField(decimal_places=2, editable=False, help_text='Equivalente contable en Bolívares', max_digits=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('representante_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('estatus', models.CharField(choices=[('completado', 'Completado'), ('anulado', 'Anulado'), ('en_revision', 'En Revisión')], db_index=True, default='completado', max_length=20)),
                ('representante_nombre', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente', models.CharField(default='BCV', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ves', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
