# Generated by Django 6.0.5 on 2026-05-21 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0001_initial'),
        ('secretaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='usuario_cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='secretaria.alumno'),
        ),
        migrations.AddField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='secretaria.alumno'),
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cobranza.bancoinstitucional'),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='pagos',
            field=models.ManyToManyField(blank=True, related_name='mensualidades_pagadas', to='cobranza.pago'),
        ),
        migrations.AddField(
            model_name='transferenciainterna',
            name='banco_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='cobranza.bancoinstitucional'),
        ),
        migrations.AddField(
            model_name='transferenciainterna',
            name='banco_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='cobranza.bancoinstitucional'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus', 'completado')), fields=('referencia',), name='unique_referencia_pago_completado'),
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('alumno', 'mes', 'anio')},
        ),
    ]
