# Generated by Django 6.0.5 on 2026-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tasa_aplicada',
            field=models.DecimalField(decimal_places=4, help_text='Tasa BCV del momento de la transacción', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='valor_bs',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
