# Generated by Django 6.0.5 on 2026-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0003_alter_pago_tasa_aplicada_alter_tasacambio_valor_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancoinstitucional',
            name='tipo',
            field=models.CharField(choices=[('general', 'General (todos los métodos)'), ('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle')], default='general', max_length=20),
        ),
    ]
