# Generated by Django 6.0.5 on 2026-05-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0005_pago_factura_id'),
        ('secretaria', '0005_normalizar_grados_seccion_unica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='factura_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CuotaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_inscripcion', to='secretaria.alumno')),
                ('pagos', models.ManyToManyField(blank=True, related_name='cuotas_inscripcion_pagadas', to='cobranza.pago')),
            ],
            options={
                'ordering': ['-periodo_escolar'],
                'unique_together': {('alumno', 'periodo_escolar')},
            },
        ),
    ]
