# Generated by Django 6.0.5 on 2026-06-03 17:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0010_pago_metodo_stripe'),
        ('secretaria', '0008_configuracionsistema_colores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmensualidad',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mensualidad', 'verbose_name_plural': 'historical mensualidads'},
        ),
        migrations.AlterModelOptions(
            name='historicalpago',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pago', 'verbose_name_plural': 'historical pagos'},
        ),
        migrations.RemoveField(
            model_name='historicalmensualidad',
            name='alumno_id',
        ),
        migrations.RemoveField(
            model_name='historicalpago',
            name='alumno_id',
        ),
        migrations.RemoveField(
            model_name='historicalpago',
            name='banco_receptor_id',
        ),
        migrations.RemoveField(
            model_name='historicalpago',
            name='usuario_receptor_id',
        ),
        migrations.AddField(
            model_name='historicalmensualidad',
            name='alumno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretaria.alumno'),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='alumno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretaria.alumno'),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='banco_receptor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobranza.bancoinstitucional'),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='usuario_receptor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmensualidad',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='historicalmensualidad',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalmensualidad',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='concepto',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad Escolar'), ('inscripcion', 'Inscripción'), ('materiales', 'Materiales'), ('actividades', 'Actividades Extraescolares'), ('multa', 'Multa'), ('otro', 'Otro')], default='mensualidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='estatus',
            field=models.CharField(choices=[('completado', 'Completado'), ('anulado', 'Anulado'), ('en_revision', 'En Revisión')], db_index=True, default='completado', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='factura_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='monto_usd',
            field=models.DecimalField(decimal_places=2, help_text='Monto captado en divisas', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='monto_ves',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Equivalente contable en Bolívares', max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='operacion_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='tasa_aplicada',
            field=models.DecimalField(decimal_places=4, help_text='Tasa BCV del momento de la transacción', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='vuelto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Vuelto entregado al representante en USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='vuelto_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Vuelto entregado al representante en Bolívares', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares')], max_length=20),
        ),
    ]
