# Generated by Django 6.0.5 on 2026-06-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0012_pago_unique_referencia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares'), ('stripe', 'Stripe (Pago Online)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares'), ('stripe', 'Stripe (Pago Online)')], max_length=20),
        ),
    ]
