# Generated by Django 6.0.4 on 2026-07-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0013_alter_historicalpago_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmensualidad',
            name='pagado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='pagado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
