# Generated by Django 6.0.5 on 2026-07-07 15:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0014_alter_historicalmensualidad_pagado_and_more'),
        ('secretaria', '0009_alter_alumno_grado_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpago',
            name='concepto',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad Escolar'), ('inscripcion', 'Inscripción'), ('solvencia', 'Solvencia'), ('materiales', 'Materiales'), ('actividades', 'Actividades Extraescolares'), ('multa', 'Multa'), ('otro', 'Otro')], default='mensualidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad Escolar'), ('inscripcion', 'Inscripción'), ('solvencia', 'Solvencia'), ('materiales', 'Materiales'), ('actividades', 'Actividades Extraescolares'), ('multa', 'Multa'), ('otro', 'Otro')], default='mensualidad', max_length=20),
        ),
        migrations.CreateModel(
            name='CuotaSolvencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_solvencia', to='secretaria.alumno')),
                ('pagos', models.ManyToManyField(blank=True, related_name='cuotas_solvencia_pagadas', to='cobranza.pago')),
            ],
            options={
                'ordering': ['-periodo_escolar'],
                'unique_together': {('alumno', 'periodo_escolar')},
            },
        ),
    ]
