# Generated by Django 6.0.5 on 2026-07-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0015_alter_historicalpago_concepto_alter_pago_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasolvencia',
            name='concepto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
