# Generated by Django 6.0.5 on 2026-07-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0016_cuotasolvencia_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpago',
            name='banco_procedencia',
            field=models.CharField(blank=True, help_text='Banco emisor del pagador (distinto de banco_receptor, que es el banco destino del colegio)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_procedencia',
            field=models.CharField(blank=True, help_text='Banco emisor del pagador (distinto de banco_receptor, que es el banco destino del colegio)', max_length=100, null=True),
        ),
    ]
