# Generated by Django 6.0.5 on 2026-07-10 03:57

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0019_historicalcuotainscripcion'),
        ('secretaria', '0011_alumno_alergico_alumno_bautizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCuotaProyectoInversion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretaria.representante')),
            ],
            options={
                'verbose_name': 'historical cuota proyecto inversion',
                'verbose_name_plural': 'historical cuota proyecto inversions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CuotaProyectoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('pagos', models.ManyToManyField(blank=True, related_name='proyectos_inversion_pagados', to='cobranza.pago')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_proyecto_inversion', to='secretaria.representante')),
            ],
            options={
                'ordering': ['-periodo_escolar'],
                'unique_together': {('representante', 'periodo_escolar')},
            },
        ),
    ]
