# Generated by Django 6.0.5 on 2026-07-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0020_historicalcuotaproyectoinversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpago',
            name='concepto',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad Escolar'), ('inscripcion', 'Inscripción'), ('solvencia', 'Solvencia'), ('materiales', 'Materiales'), ('proyecto_inversion', 'Proyecto de Inversión'), ('multa', 'Multa'), ('mixto', 'Pago Mixto (varios conceptos)'), ('otro', 'Otro')], default='mensualidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad Escolar'), ('inscripcion', 'Inscripción'), ('solvencia', 'Solvencia'), ('materiales', 'Materiales'), ('proyecto_inversion', 'Proyecto de Inversión'), ('multa', 'Multa'), ('mixto', 'Pago Mixto (varios conceptos)'), ('otro', 'Otro')], default='mensualidad', max_length=20),
        ),
    ]
