# Generated by Django 6.0.5 on 2026-07-10 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0021_alter_historicalpago_concepto_alter_pago_concepto'),
        ('secretaria', '0011_alumno_alergico_alumno_bautizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvenciaRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('origen', models.CharField(choices=[('automatica', 'Automática'), ('manual', 'Manual (Director)')], default='automatica', max_length=15)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('emitida_por', models.ForeignKey(blank=True, help_text="Solo aplica para origen='manual'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solvencias_emitidas_manualmente', to=settings.AUTH_USER_MODEL)),
                ('pago_generador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solvencias_generadas', to='cobranza.pago')),
                ('representante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='solvencia', to='secretaria.representante')),
            ],
        ),
    ]
