# Generated by Django 6.0.5 on 2026-07-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0023_banco_tipos_multiples'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpago',
            name='numero_lote',
            field=models.CharField(blank=True, help_text='Número de lote del cierre de punto de venta (agrupa varias transacciones del mismo corte/día, no es único)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_lote',
            field=models.CharField(blank=True, help_text='Número de lote del cierre de punto de venta (agrupa varias transacciones del mismo corte/día, no es único)', max_length=10, null=True),
        ),
    ]
