# Generated by Django 6.0.5 on 2026-07-22 18:27

from decimal import Decimal
from django.db import migrations, models


def backfill_monto_pagado(apps, schema_editor):
    """
    Cuotas ya marcadas pagado=True antes de que existiera el acumulador
    monto_pagado se asumen saldadas por el total (no había abonos parciales
    hasta ahora), para no romper el criterio de mora recién introducido.
    """
    CuotaProyectoInversion = apps.get_model('cobranza', 'CuotaProyectoInversion')
    CuotaProyectoInversion.objects.filter(pagado=True).update(monto_pagado=models.F('monto_usd'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0024_historicalpago_numero_lote_pago_numero_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaproyectoinversion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalcuotaproyectoinversion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(backfill_monto_pagado, noop),
    ]
