# Generated by Django 6.0.4 on 2026-07-23 01:25

from decimal import Decimal
from django.db import migrations, models


def backfill_monto_pagado(apps, schema_editor):
    """
    Cuotas ya marcadas pagado=True antes de que existiera el acumulador
    monto_pagado se asumen saldadas por el total (no había abonos parciales
    hasta ahora), para no romper el criterio de mora con el `save()` que
    ahora deriva `pagado` a partir de `monto_pagado` vs `monto_usd`.
    """
    CuotaSolvencia = apps.get_model('cobranza', 'CuotaSolvencia')
    CuotaSolvencia.objects.filter(pagado=True).update(monto_pagado=models.F('monto_usd'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0025_cuotaproyectoinversion_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasolvencia',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(backfill_monto_pagado, noop),
    ]
