# Generated by Django 6.0.5 on 2026-07-23 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0026_cuotasolvencia_monto_pagado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteRevisionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('pagos', models.ManyToManyField(related_name='lotes_revision', to='cobranza.pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_revision_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
