# Generated by Django 6.0.4 on 2026-08-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0027_loterevisioncaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionPagoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inscripcion', 'Inscripción'), ('proyecto_inversion', 'Proyecto de Inversión'), ('mes_atrasado', 'Mes Atrasado'), ('proyecto_inversion_atrasado', 'Proyecto de Inversión Atrasado')], max_length=30)),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_pago_manual', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_manuales', to='cobranza.pago')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
