# Generated by Django 6.0.5 on 2026-08-06 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0028_clasificacionpagomanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpago',
            name='fecha_pago',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
