# Generated by Django 6.0.4 on 2026-08-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0029_alter_historicalpago_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('punto_de_venta', 'Punto de Venta'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo Divisas'), ('efectivo_ves', 'Efectivo Bolívares')], max_length=20),
        ),
    ]
