# Generated by Django 6.0.4 on 2026-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0030_quitar_metodo_stripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpago',
            name='representante_documento',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='representante_documento',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
