# Generated by Django 6.0.4 on 2026-08-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0032_agregar_anulacion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroglobal',
            name='valor',
            field=models.TextField(),
        ),
    ]
