# Generated by Django 6.0.4 on 2026-09-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0033_parametroglobal_valor_textfield'),
        ('multisede', '0001_initial'),
        ('secretaria', '0016_configuracionsistema_logo_avec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaproyectoinversion',
            name='fecha_cobro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotaproyectoinversion',
            name='numero_cuota',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalcuotaproyectoinversion',
            name='fecha_cobro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcuotaproyectoinversion',
            name='numero_cuota',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TipoCargoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_defecto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidad', models.CharField(choices=[('unico', 'Único'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral')], default='unico', max_length=15)),
                ('numero_cuotas', models.PositiveSmallIntegerField(default=1)),
                ('fecha_primera_cuota', models.DateField(blank=True, null=True)),
                ('dia_cobro', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bloquea_inscripcion', models.BooleanField(default=True)),
                ('alcance', models.CharField(choices=[('todos', 'Todos los representantes'), ('grado', 'Por grado'), ('sede', 'Por sede')], default='todos', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('grados', models.ManyToManyField(blank=True, related_name='tipos_cargo_especial', to='secretaria.configuraciongrado')),
                ('sedes', models.ManyToManyField(blank=True, related_name='tipos_cargo_especial', to='multisede.sede')),
            ],
            options={
                'verbose_name': 'Tipo de Cargo Especial',
                'verbose_name_plural': 'Tipos de Cargo Especial',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cuotaproyectoinversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cuotaproyectoinversion',
            name='tipo_concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cobranza.tipocargoespecial'),
        ),
        migrations.AddField(
            model_name='historicalcuotaproyectoinversion',
            name='tipo_concepto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobranza.tipocargoespecial'),
        ),
        migrations.AlterUniqueTogether(
            name='cuotaproyectoinversion',
            unique_together={('representante', 'periodo_escolar', 'tipo_concepto', 'numero_cuota')},
        ),
    ]
