# Generated by Django 6.0.4 on 2026-09-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0036_tipo_concepto_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmensualidad',
            name='monto_original_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalmensualidad',
            name='porcentaje_beca_aplicado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='monto_original_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='porcentaje_beca_aplicado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
