# Generated by Django 6.0.4 on 2026-09-02 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0038_backfill_monto_original_mensualidad'),
        ('multisede', '0001_initial'),
        ('secretaria', '0019_backfill_becas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='unique_referencia_pago_activo',
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus__in', ['completado', 'en_revision'])), fields=('referencia', 'metodo_pago', 'banco_receptor'), name='unique_referencia_metodo_banco_pago_activo'),
        ),
    ]
