# Generated by Django 6.0.4 on 2026-09-02 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0039_remove_pago_unique_referencia_pago_activo_and_more'),
        ('multisede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaRecargoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_recargo', to='cobranza.mensualidad')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_recargo', to='cobranza.pago')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ReglaRecargoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('recargo', 'Recargo'), ('descuento', 'Descuento')], default='recargo', max_length=20)),
                ('modo_calculo', models.CharField(choices=[('monto_fijo_usd', 'Monto fijo (USD)'), ('porcentaje', 'Porcentaje')], default='monto_fijo_usd', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_aplicacion', models.PositiveSmallIntegerField(help_text='Día del mes de la mensualidad a partir del cual (inclusive) se considera tardía. En meses cortos se topa al último día real del mes (igual criterio que cobranza/mora.py::calcular_dias_atraso).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('modificada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, help_text='Vacío = regla global (aplica a alumnos sin regla propia de sede).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_recargo_pago', to='multisede.sede')),
            ],
            options={
                'verbose_name': 'Regla de Recargo por Pago Tardío',
                'verbose_name_plural': 'Reglas de Recargo por Pago Tardío',
                'ordering': ['-creada_en'],
            },
        ),
    ]
