# Generated by Django 6.0.4 on 2026-09-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0040_linearecargopago_reglarecargopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglarecargopago',
            name='sede',
        ),
    ]
