# Generated by Django 6.0.4 on 2026-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0041_eliminar_sede_reglarecargopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotainscripcion',
            name='monto_personalizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cuotaproyectoinversion',
            name='monto_personalizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalcuotainscripcion',
            name='monto_personalizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalcuotaproyectoinversion',
            name='monto_personalizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalmensualidad',
            name='monto_personalizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='monto_personalizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
