# Generated by Django 6.0.4 on 2026-09-07 21:10

from decimal import Decimal
from django.db import migrations, models


def backfill_monto_pagado(apps, schema_editor):
    """
    Mensualidades ya marcadas pagado=True antes de que existiera el
    acumulador monto_pagado se asumen saldadas por el total (no había
    abonos parciales hasta ahora), mismo criterio que
    0025_cuotaproyectoinversion_monto_pagado.py. Las impagas quedan en
    0.00, que ya es el default del campo.
    """
    Mensualidad = apps.get_model('cobranza', 'Mensualidad')
    Mensualidad.objects.filter(pagado=True).update(monto_pagado=models.F('monto_usd'))
    Mensualidad.objects.filter(pagado=False).update(monto_pagado=Decimal('0.00'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0042_cuotainscripcion_monto_personalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmensualidad',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(backfill_monto_pagado, noop),
    ]
