# Generated by Django 6.0.4 on 2026-09-15 20:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0043_historicalmensualidad_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglarecargopago',
            name='dia_desde',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Solo tipo='descuento'. Primer día del mes de la mensualidad (inclusive) en que aplica el monto final `valor`. Igual tope de fin de mes que dia_aplicacion.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='reglarecargopago',
            name='dia_hasta',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Solo tipo='descuento'. Último día del rango (inclusive).", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='reglarecargopago',
            name='dia_aplicacion',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Solo tipo='recargo'. Día del mes de la mensualidad a partir del cual (inclusive) se considera tardía. En meses cortos se topa al último día real del mes (igual criterio que cobranza/mora.py::calcular_dias_atraso).", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.CreateModel(
            name='LineaDescuentoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_descontado_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_descuento', to='cobranza.mensualidad')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_descuento', to='cobranza.pago')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
