# Generated by Django 6.0.4 on 2026-09-21 20:00

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def marcar_pagadas_como_saldadas(apps, schema_editor):
    """Las inscripciones ya pagadas eran todo-o-nada: se saldaron por su
    monto completo. Sin esto, CuotaInscripcion.save() las reabriría."""
    CuotaInscripcion = apps.get_model('cobranza', 'CuotaInscripcion')
    CuotaInscripcion.objects.filter(pagado=True).update(monto_pagado=F('monto_usd'))


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0044_reglarecargopago_dia_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotainscripcion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalcuotainscripcion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(marcar_pagadas_como_saldadas, migrations.RunPython.noop),
    ]
