# Generated by Django 6.0.4 on 2026-10-08 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0046_bancoinstitucional_portal_metodos'),
        ('multisede', '0001_initial'),
        ('secretaria', '0031_normalizar_becas_totales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='unique_referencia_metodo_banco_pago_activo',
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus__in', ['completado', 'en_revision']), models.Q(('metodo_pago', 'punto_de_venta'), _negated=True)), fields=('referencia', 'metodo_pago', 'banco_receptor'), name='unique_referencia_metodo_banco_pago_activo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus__in', ['completado', 'en_revision']), ('metodo_pago', 'punto_de_venta')), fields=('referencia', 'metodo_pago', 'banco_receptor', 'numero_lote'), name='unique_referencia_lote_pos_pago_activo'),
        ),
    ]
