# Generated by Django 6.0.4 on 2026-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0046_bancoinstitucional_portal_metodos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancoinstitucional',
            name='activo_conciliador',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bancoinstitucional',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='bancoinstitucional',
            name='formato_estado_cuenta',
            field=models.CharField(choices=[('generico', 'Genérico'), ('bancaribe', 'Bancaribe'), ('banesco', 'Banesco'), ('tesoro', 'Banco del Tesoro'), ('bdt', 'Banco Digital de los Trabajadores')], default='generico', max_length=20),
        ),
    ]
