# Generated by Django 6.0.4 on 2026-10-08 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0046_bancoinstitucional_portal_metodos'),
        ('multisede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCobranzaInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('modo_sombra', models.BooleanField(default=True, help_text='Con el módulo encendido evalúa y registra, pero no envía.')),
                ('etapas_envio_activas', models.JSONField(blank=True, default=list)),
                ('activado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobranza_inteligente', to='multisede.sede')),
            ],
            options={
                'verbose_name': 'Configuración de Cobranza Inteligente',
            },
        ),
    ]
