# Generated by Django 6.0.4 on 2026-10-08 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0047_configuracion_cobranza_inteligente'),
        ('multisede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('preventiva', 'Preventiva'), ('vencida', 'Vencida'), ('seguimiento', 'Seguimiento'), ('prioritaria', 'Prioritaria'), ('critica', 'Crítica'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], db_index=True, default='preventiva', max_length=12)),
                ('estado_previo_pausa', models.CharField(blank=True, default='', max_length=12)),
                ('motivo_pausa', models.CharField(blank=True, default='', max_length=200)),
                ('motivo_cierre', models.CharField(blank=True, default='', max_length=30)),
                ('ultima_accion_en', models.DateTimeField(blank=True, null=True)),
                ('proxima_accion', models.CharField(blank=True, default='', max_length=100)),
                ('proxima_accion_fecha', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('mensualidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo', to='cobranza.mensualidad')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_cobranza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo de cobranza',
                'verbose_name_plural': 'Ciclos de cobranza',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='EventoCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=30)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cobranza.ciclocobranza')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='multisede.sede')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
