# Generated by Django 6.0.4 on 2026-10-07 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0048_bancos_formato_estado_cuenta_datos'),
        ('portal', '0006_remove_comprobantepago_unique_referencia_comprobante_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_uuid', models.UUIDField(db_index=True)),
                ('referencia_banco', models.CharField(max_length=100)),
                ('fecha_banco', models.DateField()),
                ('monto_banco_ves', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_sistema_ves', models.DecimalField(decimal_places=2, max_digits=20)),
                ('diferencia_ves', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tolerancia_aplicada_ves', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuera_tolerancia', models.BooleanField(db_index=True, default=False)),
                ('observacion', models.TextField(blank=True, default='')),
                ('archivo_estado_cuenta', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='loterevisioncaja',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('finalizado', 'Finalizado')], db_index=True, default='finalizado', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='loterevisioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierto')), fields=('usuario',), name='unico_lote_abierto_por_usuario'),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='cobranza.bancoinstitucional'),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='comprobante_aprobado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones', to='portal.comprobantepago'),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='cobranza.loterevisioncaja'),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_bancarias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='conciliacionbancaria',
            constraint=models.UniqueConstraint(fields=('operacion_uuid',), name='unica_conciliacion_por_operacion'),
        ),
        migrations.AddConstraint(
            model_name='conciliacionbancaria',
            constraint=models.UniqueConstraint(fields=('banco', 'referencia_banco', 'fecha_banco'), name='unica_linea_banco_conciliada'),
        ),
    ]
