# Generated by Django 6.0.4 on 2026-10-08 13:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0048_ciclo_cobranza_evento_ciclo'),
        ('multisede', '0001_initial'),
        ('secretaria', '0031_normalizar_becas_totales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('etapa', models.CharField(choices=[('preventiva', 'Preventiva'), ('temprana', 'Temprana'), ('prioritaria', 'Prioritaria y crítica')], max_length=12)),
                ('dia_relativo', models.SmallIntegerField()),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('ambos', 'WhatsApp y email'), ('interno', 'Interno')], max_length=10)),
                ('plantilla', models.CharField(max_length=40)),
                ('saldo_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10)),
                ('destinatario', models.CharField(choices=[('representante', 'Representante'), ('responsable', 'Responsable'), ('director', 'Director')], default='representante', max_length=14)),
                ('activa', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_cobranza', to='multisede.sede')),
            ],
            options={
                'ordering': ['dia_relativo'],
            },
        ),
        migrations.CreateModel(
            name='EnvioCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('simulado', 'Simulado (modo sombra)'), ('pendiente', 'Pendiente'), ('reintento', 'Reintento'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('omitido', 'Omitido'), ('cancelado', 'Cancelado')], db_index=True, max_length=10)),
                ('canal', models.CharField(blank=True, default='', max_length=10)),
                ('motivo_omision', models.CharField(blank=True, default='', max_length=40)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('proximo_intento', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cobranza', to='secretaria.representante')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='cobranza.reglacobranza')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BajaCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas_cobranza', to='secretaria.representante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('representante', 'canal'), name='uniq_baja_cobranza_rep_canal')],
            },
        ),
        migrations.AddConstraint(
            model_name='reglacobranza',
            constraint=models.UniqueConstraint(fields=('sede', 'dia_relativo'), name='uniq_regla_cobranza_sede_dia'),
        ),
        migrations.AddConstraint(
            model_name='enviocobranza',
            constraint=models.UniqueConstraint(fields=('representante', 'regla', 'fecha'), name='uniq_envio_cobranza_rep_regla_fecha'),
        ),
    ]
