# Generated by Django 6.0.4 on 2026-10-07 14:28

import cobranza.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0049_lotes_abiertos_y_conciliacion_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancoinstitucional',
            name='config_estado_cuenta',
            field=models.JSONField(blank=True, default=dict, validators=[cobranza.models.validar_config_estado_cuenta]),
        ),
    ]
