# Generated by Django 6.0.4 on 2026-10-08 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0049_reglas_envios_bajas_cobranza'),
        ('multisede', '0001_initial'),
        ('secretaria', '0031_normalizar_becas_totales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('cumplido', 'Cumplido'), ('incumplido', 'Incumplido'), ('cancelado', 'Cancelado')], db_index=True, default='vigente', max_length=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciclos', models.ManyToManyField(related_name='convenios', to='cobranza.ciclocobranza')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios_cobranza', to='secretaria.representante')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaBaseCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobrado_al_vencimiento_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mora_7_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mora_15_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mora_30_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horas_semanales_cobranza', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('periodo_desde', models.DateField(blank=True, null=True)),
                ('periodo_hasta', models.DateField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sede', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea_base_cobranza', to='multisede.sede')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('pagada_en', models.DateTimeField(blank=True, null=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='cobranza.conveniopago')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('convenio', 'numero'), name='uniq_cuota_convenio_numero')],
            },
        ),
    ]
