# Generated by Django 6.0.4 on 2026-10-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cobranza", "0047_pago_referencia_pos_con_lote"),
        ("cobranza", "0050_convenio_linea_base_cobranza"),
    ]

    operations = []
