# Generated by Django 6.0.4 on 2026-10-07 16:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multisede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='finanzas.categoriagasto')),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'ordering': ['padre_id', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'Bolívares')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='finanzas.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_categoria_creados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_categoria', to='multisede.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Presupuesto por categoría',
                'verbose_name_plural': 'Presupuestos por categoría',
                'ordering': ['-anio', '-mes', 'categoria__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('rif', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RIF debe tener el formato V-12345678-9.', regex='^[VEJPG]-\\d{8}-\\d$')])),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50)),
                ('pago_movil', models.CharField(blank=True, max_length=50)),
                ('zelle', models.EmailField(blank=True, max_length=254)),
                ('condicion_habitual', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('dias_credito_habitual', models.PositiveSmallIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_predeterminados', to='finanzas.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriagasto',
            constraint=models.UniqueConstraint(fields=('nombre', 'padre'), name='finanzas_categoria_nombre_padre_unico'),
        ),
        migrations.AddConstraint(
            model_name='presupuestocategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'sede', 'anio', 'mes', 'moneda'), name='finanzas_presupuesto_categoria_sede_periodo_moneda_unico'),
        ),
        migrations.AddConstraint(
            model_name='presupuestocategoria',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='finanzas_presupuesto_mes_valido'),
        ),
    ]
