# Generated by Django 6.0.5 on 2026-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='detalles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
