# Generated by Django 6.0.5 on 2026-05-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('asignacion', 'Asignación'), ('deduccion', 'Deducción')], max_length=15)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fijo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_personal', models.CharField(choices=[('administrativo', 'Administrativo'), ('obrero', 'Obrero'), ('docente', 'Docente'), ('directivo', 'Directivo')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo_base_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('es_pensionado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateField(auto_now_add=True)),
                ('mes_correspondiente', models.PositiveSmallIntegerField()),
                ('anio_correspondiente', models.PositiveSmallIntegerField()),
                ('monto_sso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_lph', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_cestaticket', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bono_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasa_pago_bono', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagar_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
            ],
        ),
    ]
