# Generated by Django 6.0.4 on 2026-08-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_alter_empleado_sueldo_base_ves'),
        ('rrhh', '0007_alter_empleado_tipo_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empleado_rrhh',
            field=models.ForeignKey(blank=True, help_text='Vínculo opcional con el Empleado correspondiente en el módulo de RRHH.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_nomina', to='rrhh.empleado'),
        ),
    ]
