# Generated by Django 6.0.4 on 2026-08-27 17:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_empleado_empleado_rrhh'),
        ('rrhh', '0007_alter_empleado_tipo_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroLegalNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(unique=True)),
                ('porcentaje_sso', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('porcentaje_lph', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Parámetro legal de nómina',
                'verbose_name_plural': 'Parámetros legales de nómina',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.AddField(
            model_name='registronomina',
            name='porcentaje_lph_aplicado',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=6),
        ),
        migrations.AddField(
            model_name='registronomina',
            name='porcentaje_sso_aplicado',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.04'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_rrhh',
            field=models.ForeignKey(blank=True, help_text='Ficha maestra correspondiente en el módulo de RRHH.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_nomina', to='rrhh.empleado'),
        ),
        migrations.AddConstraint(
            model_name='registronomina',
            constraint=models.UniqueConstraint(fields=('empleado', 'mes_correspondiente', 'anio_correspondiente'), name='nomina_empleado_periodo_unico'),
        ),
    ]
