# Generated by Django 6.0.4 on 2026-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_parametrolegalnomina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronomina',
            name='porcentaje_lph_aplicado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='registronomina',
            name='porcentaje_sso_aplicado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
