# Generated by Django 6.0.4 on 2026-09-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_arreglos_auditoria'),
        ('secretaria', '0025_configuracionsistema_convenio_nomina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptonomina',
            options={'ordering': ['orden_aplicacion', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='conceptonomina',
            name='fijo',
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='alcance_personal',
            field=models.CharField(choices=[('todos', 'Todos'), ('docente', 'Docente'), ('administrativo', 'Administrativo')], default='todos', max_length=20),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='base_calculo',
            field=models.CharField(choices=[('sueldo_base', 'Porcentaje del sueldo base'), ('monto_fijo', 'Monto fijo'), ('otro_concepto', 'Igual a otro concepto (ej. prima geográfica = prima docente)')], default='monto_fijo', max_length=20),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='concepto_referencia',
            field=models.ForeignKey(blank=True, help_text="Solo si base_calculo='otro_concepto': el concepto del que deriva su monto.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivados', to='nomina.conceptonomina'),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='configuracion',
            field=models.ForeignKey(blank=True, help_text='Configuración del sistema a la que pertenece este concepto. Nulo = concepto universal de referencia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_nomina', to='secretaria.configuracionsistema'),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='convenio',
            field=models.CharField(blank=True, default='', help_text="Vacío = universal (Capa 1, disponible en cualquier convenio). 'avec_ve' = exclusivo del convenio AVEC (Capa 2).", max_length=20),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('VES', 'VES')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='orden_aplicacion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='vigente_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
