# Generated by Django 6.0.4 on 2026-09-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_alter_conceptonomina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptonomina',
            name='codigo',
            field=models.CharField(blank=True, choices=[('', 'Sin código (concepto libre, no afecta cálculo automático)'), ('ANTIGUEDAD_PCT_ANIO', 'Antigüedad — % del sueldo base por año de servicio'), ('HIJO_FIJO', 'Prima por hijo — monto fijo por hijo'), ('ASISTENCIAL_FIJO', 'Prima asistencial — monto fijo')], default='', help_text='Si se selecciona, este concepto alimenta directamente el cálculo de nómina del frontend (calcAVEC) en vez de ser solo informativo.', max_length=30),
        ),
        migrations.AddField(
            model_name='registronomina',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', help_text='Un registro cerrado ya no se recalcula automáticamente si cambian los datos maestros del empleado.', max_length=10),
        ),
    ]
