# Generated by Django 6.0.4 on 2026-09-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_conceptonomina_codigo_registronomina_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('fijo', 'Fijo'), ('temporal', 'Temporal'), ('honorarios', 'Honorarios')], default='', max_length=20),
        ),
    ]
