# Generated by Django 6.0.5 on 2026-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_tipocargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
