# Generated by Django 6.0.5 on 2026-05-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_empleado_cuenta_telefono_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco de Nómina',
                'verbose_name_plural': 'Bancos de Nómina',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='rrhh.banconomina'),
        ),
    ]
