# Generated by Django 6.0.5 on 2026-06-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_empleado_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='anos_servicio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='categoria_docente',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_semanales',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nivel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_hijos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_personal',
            field=models.CharField(choices=[('docente', 'Docente'), ('administrativo', 'Administrativo'), ('apoyo', 'Personal de Apoyo')], default='docente', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
