# Generated by Django 6.0.5 on 2026-06-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_empleado_anos_servicio_empleado_categoria_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_personal',
            field=models.CharField(choices=[('docente', 'Docente'), ('apoyo', 'Personal de Apoyo'), ('administrativo', 'Administrativo')], default='docente', max_length=20),
        ),
    ]
