# Generated by Django 6.0.4 on 2026-08-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_alter_empleado_tipo_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_personal',
            field=models.CharField(choices=[('docente', 'Docente'), ('apoyo', 'Personal de Apoyo'), ('administrativo', 'Administrativo'), ('directivo', 'Directivo'), ('obrero', 'Obrero')], default='docente', max_length=20),
        ),
    ]
