# Generated by Django 6.0.4 on 2026-08-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_alter_empleado_tipo_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='banconomina',
            name='codigo_bancario',
            field=models.CharField(blank=True, default='', help_text='Código de 4 dígitos del banco en Venezuela (ej. 0114 = Bancaribe).', max_length=4),
        ),
    ]
