# Generated by Django 6.0.4 on 2026-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_arreglos_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='postgrado',
            field=models.CharField(blank=True, choices=[('', 'Ninguno'), ('ESPE', 'Especialización'), ('MAES', 'Maestría'), ('DOCT', 'Doctorado')], default='', max_length=4),
        ),
    ]
