import { Link } from 'react-router-dom';
import { Bell, CheckCircle2, ChevronRight, CircleDollarSign, TrendingDown } from 'lucide-react';

const WidgetFamiliaHoy = ({ deuda = 0, avisos = 0, alertas = [], alumnoActivo, onPagar, className = '' }) => {
  const items = [];
  if (deuda > 0) items.push({ id: 'pago', Icon: CircleDollarSign, tone: 'bg-[var(--yellow-light)] text-[var(--yellow)]', title: 'Tienes un pago pendiente', detail: 'Puedes enviar el comprobante por transferencia.', action: 'Pagar ahora', onClick: onPagar });
  if (avisos > 0) items.push({ id: 'avisos', Icon: Bell, tone: 'bg-sky-50 text-sky-700', title: `${avisos} aviso${avisos === 1 ? '' : 's'} por leer`, detail: 'Mantente al día con las comunicaciones del colegio.', action: 'Leer avisos', to: '/portal/comunicaciones' });
  if (alertas.length > 0) { const a = alertas[0]; items.push({ id: 'rendimiento', Icon: TrendingDown, tone: 'bg-violet-50 text-violet-700', title: `${a.alumno_nombre || alumnoActivo?.nombre || 'Tu estudiante'} necesita acompañamiento`, detail: `${a.materia_nombre || 'Una materia'} · promedio ${a.promedio ?? 'por revisar'}`, action: 'Ver rendimiento', to: '/portal/rendimiento' }); }

  return <section className={`portal-card overflow-hidden ${className}`} aria-labelledby="familia-hoy"><div className="flex items-start justify-between px-4 pt-4 pb-3"><div><h2 id="familia-hoy" className="text-sm font-semibold text-[var(--jet)]">Para tu familia, hoy</h2><p className="mt-0.5 text-xs text-[var(--ash)]">Información simple para saber qué hacer primero.</p></div><span className="text-[10px] text-[var(--ash)]">Actualizado ahora</span></div>{items.length === 0 ? <div className="px-4 py-7 text-center"><CheckCircle2 size={25} className="mx-auto text-[var(--green)]" /><p className="mt-2 text-sm font-medium text-[var(--jet-mid)]">Todo está en orden</p><p className="mt-1 text-xs text-[var(--ash)]">No hay acciones pendientes por ahora.</p></div> : <div className="divide-y divide-[var(--border)]">{items.map(({ id, Icon, tone, title, detail, action, to, onClick }) => { const inner = <><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${tone}`}><Icon size={16} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[var(--jet)]">{title}</p><p className="truncate text-xs text-[var(--ash)]">{detail}</p></div><span className="hidden sm:block text-xs font-semibold text-[var(--portal-primary)]">{action}</span><ChevronRight size={16} className="shrink-0 text-[var(--ash)]" /></>; return to ? <Link key={id} to={to} className="flex items-center gap-3 px-4 py-3 hover:bg-[var(--surface-sunken)]">{inner}</Link> : <button key={id} onClick={onClick} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-[var(--surface-sunken)]">{inner}</button>; })}</div>}</section>;
};

export default WidgetFamiliaHoy;
