# Generated by Django 6.0.4 on 2026-10-07 16:40

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(default='unidad', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo frecuente',
                'verbose_name_plural': 'Artículos frecuentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('antes', models.JSONField(blank=True, default=dict)),
                ('despues', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Bitácora de egreso',
                'verbose_name_plural': 'Bitácoras de egreso',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='egresos/comprobantes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])])),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('pago', 'Comprobante de pago')], default='documento', max_length=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comprobante de egreso',
                'verbose_name_plural': 'Comprobantes de egreso',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEgresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_activo', models.BooleanField(default=True)),
                ('umbral_alerta_variacion', models.DecimalField(decimal_places=4, default=Decimal('15.0000'), max_digits=7)),
                ('alicuota_iva_default', models.DecimalField(decimal_places=4, default=Decimal('16.0000'), max_digits=7)),
                ('alicuota_igtf_default', models.DecimalField(decimal_places=4, default=Decimal('3.0000'), max_digits=7)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de egresos',
                'verbose_name_plural': 'Configuración de egresos',
            },
        ),
        migrations.CreateModel(
            name='DetallePagoCuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'Bolívares')], max_length=3)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('pago_movil', 'Pago móvil'), ('punto_de_venta', 'Punto de venta'), ('zelle', 'Zelle'), ('efectivo_usd', 'Efectivo USD'), ('efectivo_ves', 'Efectivo VES'), ('otro', 'Otro')], max_length=20)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto_documento', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_ves', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comprobantes', models.JSONField(blank=True, default=list, help_text='Rutas/metadatos inmutables de comprobantes del abono.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detalle de pago de cuenta por pagar',
                'verbose_name_plural': 'Detalles de pago de cuentas por pagar',
                'ordering': ['fecha_pago', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('nota_credito', 'Nota de crédito'), ('recibo', 'Recibo'), ('otro', 'Otro')], default='factura', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=80)),
                ('numero_control', models.CharField(blank=True, max_length=80)),
                ('fecha_emision', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('descripcion', models.TextField(blank=True)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'Bolívares')], default='USD', max_length=3)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('motivo_cambio_tasa', models.TextField(blank=True)),
                ('total_documento', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('porcentaje_iva', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('monto_igtf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('aplica_igtf', models.BooleanField(default=False)),
                ('retiene_iva', models.BooleanField(default=False)),
                ('porcentaje_retencion_iva', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('monto_retencion_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('retiene_islr', models.BooleanField(default=False)),
                ('porcentaje_retencion_islr', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('monto_retencion_islr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('condicion', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('dias_credito', models.PositiveSmallIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_egreso', models.DateField(blank=True, db_index=True, null=True)),
                ('tasa_pago', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('monto_usd_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_ves_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia bancaria'), ('pago_movil', 'Pago móvil'), ('punto_de_venta', 'Punto de venta'), ('zelle', 'Zelle'), ('efectivo_usd', 'Efectivo USD'), ('efectivo_ves', 'Efectivo VES'), ('otro', 'Otro')], max_length=20)),
                ('banco_pago', models.CharField(blank=True, max_length=100)),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_pago', 'Pendiente de pago'), ('registrado', 'Registrado'), ('anulado', 'Anulado')], db_index=True, default='borrador', max_length=20)),
                ('origen', models.CharField(choices=[('factura', 'Factura de contado'), ('cuenta_por_pagar', 'Cuenta por pagar')], default='factura', max_length=20)),
                ('cuenta_por_pagar_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha_egreso', '-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RenglonEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Renglón de egreso',
                'verbose_name_plural': 'Renglones de egreso',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
