# Generated by Django 6.0.4 on 2026-10-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresos', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('multisede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulofrecuente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_frecuentes', to='finanzas.categoriagasto'),
        ),
        migrations.AddField(
            model_name='articulofrecuente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_frecuentes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulofrecuente',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_frecuentes', to='finanzas.proveedor'),
        ),
        migrations.AddField(
            model_name='bitacoraegreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_egreso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobanteegreso',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_egreso_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobanteegreso',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_egreso_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionegresos',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_egresos_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egreso',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egreso',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='finanzas.categoriagasto'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egreso',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='finanzas.proveedor'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='multisede.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='detallepagocuentaporpagar',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cuenta_por_pagar', to='egresos.egreso'),
        ),
        migrations.AddField(
            model_name='comprobanteegreso',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='egresos.egreso'),
        ),
        migrations.AddField(
            model_name='bitacoraegreso',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacora', to='egresos.egreso'),
        ),
        migrations.AddField(
            model_name='renglonegreso',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renglones', to='egresos.articulofrecuente'),
        ),
        migrations.AddField(
            model_name='renglonegreso',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renglones', to='egresos.egreso'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['fecha_egreso'], name='egresos_egr_fecha_e_2b687a_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['fecha_emision'], name='egresos_egr_fecha_e_fa464f_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['sede'], name='egresos_egr_sede_id_3bbf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['estado'], name='egresos_egr_estado_de00e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='egreso',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('estado', 'anulado'), _negated=True), models.Q(('numero_documento', ''), _negated=True)), fields=('proveedor', 'tipo_documento', 'numero_documento'), name='egreso_proveedor_tipo_numero_activo_unico'),
        ),
        migrations.AddConstraint(
            model_name='egreso',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'cuenta_por_pagar'), models.Q(('estado', 'anulado'), _negated=True)), fields=('cuenta_por_pagar_id',), name='egreso_cxp_activa_unica'),
        ),
        migrations.AddConstraint(
            model_name='egreso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'registrado'), _negated=True), ('fecha_egreso__isnull', False), _connector='OR'), name='egreso_registrado_requiere_fecha'),
        ),
    ]
