# Generated by Django 6.0.4 on 2026-07-28 01:52

import comunicacion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
        ('portal', '0004_alter_comprobantepago_estatus_and_more'),
        ('secretaria', '0016_configuracionsistema_logo_avec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='mensajes/', validators=[comunicacion.models.validar_tamano_adjunto])),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_directos', to='secretaria.alumno')),
                ('destinatario_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destinatario_representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.representanteuser')),
                ('remitente_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('remitente_representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to='portal.representanteuser')),
            ],
            options={
                'ordering': ['fecha'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('remitente_docente__isnull', False), ('remitente_representante__isnull', True)), models.Q(('remitente_docente__isnull', True), ('remitente_representante__isnull', False)), _connector='OR'), name='mensaje_un_solo_remitente')],
            },
        ),
    ]
