# Generated by Django 6.0.4 on 2026-10-07 20:46

import cuentas_pagar.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0002_categorias_iniciales'),
        ('multisede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRecordatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antes', models.JSONField(default=cuentas_pagar.models.dias_recordatorio_default)),
                ('ventana_por_vencer', models.PositiveSmallIntegerField(default=7)),
                ('frecuencia_vencidas_dias', models.PositiveSmallIntegerField(default=3)),
                ('max_aplazamientos_sin_director', models.PositiveSmallIntegerField(default=2)),
                ('bandeja_activa', models.BooleanField(default=True)),
                ('email_activo', models.BooleanField(default=True)),
                ('whatsapp_activo', models.BooleanField(default=False)),
                ('canales', models.JSONField(blank=True, default=list)),
                ('roles_destino', models.JSONField(blank=True, default=list)),
                ('resumen_diario_activo', models.BooleanField(default=False)),
                ('hora_resumen', models.TimeField(default=datetime.time(7, 0))),
                ('requiere_aprobacion_pago_grande', models.BooleanField(default=False)),
                ('umbral_aprobacion_usd', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=14)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_cxp_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('usuarios_destino', models.ManyToManyField(blank=True, related_name='configuraciones_recordatorios_cxp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('origen', models.CharField(choices=[('factura', 'Factura'), ('manual', 'Manual'), ('recurrente', 'Recurrente')], default='manual', max_length=12)),
                ('concepto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'Bolívares')], default='USD', max_length=3)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('monto_documento', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, upload_to='cuentas_pagar/documentos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])])),
                ('etiquetas', models.JSONField(blank=True, default=list)),
                ('monto_por_confirmar', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], db_index=True, default='pendiente', max_length=10)),
                ('recordatorio_pospuesto_hasta', models.DateField(blank=True, null=True)),
                ('veces_aplazada', models.PositiveSmallIntegerField(default=0)),
                ('egreso_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('periodo', models.CharField(blank=True, help_text='YYYY-MM', max_length=7)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cxp_anuladas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='finanzas.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cxp_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='finanzas.proveedor')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cxp_responsable', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='multisede.sede')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvisoBandeja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_cxp', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avisos_bandeja', to='cuentas_pagar.cuentaporpagar')),
            ],
        ),
        migrations.CreateModel(
            name='AplazamientoCxP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateField()),
                ('fecha_nueva', models.DateField()),
                ('motivo', models.TextField()),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplazamientos_cxp_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplazamientos_cxp_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplazamientos', to='cuentas_pagar.cuentaporpagar')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaCuentaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cuentas_pagar.cuentaporpagar')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCxP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='cuentas_pagar.cuentaporpagar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cxp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'Bolívares')], max_length=3)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('motivo_cambio_tasa', models.TextField(blank=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('pago_movil', 'Pago móvil'), ('punto_de_venta', 'Punto de venta'), ('zelle', 'Zelle'), ('efectivo_usd', 'Efectivo USD'), ('efectivo_ves', 'Efectivo VES'), ('otro', 'Otro')], max_length=20)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('nota', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('valido', 'Válido'), ('anulado', 'Anulado'), ('por_aprobar', 'Por aprobar')], default='valido', max_length=12)),
                ('pago_multiple', models.UUIDField(blank=True, db_index=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cxp_anulados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cuentas_pagar.cuentaporpagar')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cuentas_pagar.cuotacuentapagar')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cxp_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_pago', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComprobantePagoCxP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cuentas_pagar/comprobantes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])])),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_cxp_subidos', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='cuentas_pagar.pagocuentapagar')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('concepto', models.CharField(max_length=255)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'Bolívares')], default='USD', max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('dia_emision', models.PositiveSmallIntegerField(default=1)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_cxp', to='finanzas.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_cxp_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_cxp', to='finanzas.proveedor')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_cxp', to='multisede.sede')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_generadas', to='cuentas_pagar.plantillarecurrente'),
        ),
        migrations.CreateModel(
            name='RecordatorioEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('bandeja', 'Bandeja'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=12)),
                ('tipo', models.CharField(max_length=24)),
                ('fecha_referencia', models.DateField()),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.CharField(blank=True, max_length=255)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordatorios_enviados', to='cuentas_pagar.cuentaporpagar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cuotacuentapagar',
            constraint=models.UniqueConstraint(fields=('cuenta', 'numero'), name='cxp_cuota_numero_unico'),
        ),
        migrations.AddIndex(
            model_name='pagocuentapagar',
            index=models.Index(fields=['cuenta', 'estado'], name='cuentas_pag_cuenta__801f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocuentapagar',
            index=models.Index(fields=['fecha_pago'], name='cuentas_pag_fecha_p_8ee19d_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['fecha_vencimiento'], name='cuentas_pag_fecha_v_21594a_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['estado'], name='cuentas_pag_estado_bc343f_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['sede'], name='cuentas_pag_sede_id_17e128_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['proveedor'], name='cuentas_pag_proveed_436cbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.UniqueConstraint(condition=models.Q(('plantilla__isnull', False)), fields=('plantilla', 'periodo'), name='cxp_plantilla_periodo_unico'),
        ),
        migrations.AddConstraint(
            model_name='recordatorioenviado',
            constraint=models.UniqueConstraint(fields=('cuenta', 'canal', 'tipo', 'fecha_referencia'), name='cxp_recordatorio_unico'),
        ),
    ]
