# Generated by Django 6.0.4 on 2026-10-07 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_pagar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionrecordatorios',
            name='hora_recordatorios',
            field=models.TimeField(default=datetime.time(7, 30)),
        ),
    ]
