import apiClient from '../api/apiClient';

export const listarCuentas = (params = {}) => apiClient.get('cuentas-por-pagar/', { params });
export const obtenerCuenta = (cuentaId) => apiClient.get(`cuentas-por-pagar/${cuentaId}/`);
export const crearCuenta = (body) => apiClient.post('cuentas-por-pagar/', body);
export const actualizarCuenta = (cuentaId, body) => apiClient.patch(`cuentas-por-pagar/${cuentaId}/`, body);
export const pagarCuenta = (cuentaId, body) => apiClient.post(`cuentas-por-pagar/${cuentaId}/pagar/`, body);
export const aplazarCuenta = (cuentaId, body) => apiClient.post(`cuentas-por-pagar/${cuentaId}/aplazar/`, body);
export const posponerRecordatorio = (cuentaId, body) => apiClient.post(`cuentas-por-pagar/${cuentaId}/posponer-recordatorio/`, body);
export const acuerdoCuotas = (cuentaId, body) => apiClient.post(`cuentas-por-pagar/${cuentaId}/acuerdo-cuotas/`, body);
export const confirmarMonto = (cuentaId, body) => apiClient.post(`cuentas-por-pagar/${cuentaId}/confirmar-monto/`, body);
export const anularCuenta = (cuentaId, body) => apiClient.post(`cuentas-por-pagar/${cuentaId}/anular/`, body);
export const duplicarCuenta = (cuentaId) => apiClient.post(`cuentas-por-pagar/${cuentaId}/duplicar/`);
export const listarPagos = (cuentaId) => apiClient.get(`cuentas-por-pagar/${cuentaId}/pagos/`);
export const anularPago = (pagoId, body) => apiClient.post(`cuentas-por-pagar/pagos/${pagoId}/anular/`, body);
export const aprobarPago = (pagoId) => apiClient.post(`cuentas-por-pagar/pagos/${pagoId}/aprobar/`);
export const rechazarPago = (pagoId, motivo) => apiClient.post(`cuentas-por-pagar/pagos/${pagoId}/rechazar/`, { motivo });
export const subirComprobantePago = (pagoId, form) => apiClient.post(`cuentas-por-pagar/pagos/${pagoId}/adjuntos/`, form, { headers: { 'Content-Type': 'multipart/form-data' } });
export const pagarMultiple = (body) => apiClient.post('cuentas-por-pagar/pagos-multiples/', body);
export const listarPlantillas = (params = {}) => apiClient.get('cuentas-por-pagar/plantillas/', { params });
export const crearPlantilla = (body) => apiClient.post('cuentas-por-pagar/plantillas/', body);
export const actualizarPlantilla = (plantillaId, body) => apiClient.patch(`cuentas-por-pagar/plantillas/${plantillaId}/`, body);
export const obtenerConfiguracionRecordatorios = () => apiClient.get('cuentas-por-pagar/configuracion/');
export const actualizarConfiguracionRecordatorios = (body) => apiClient.patch('cuentas-por-pagar/configuracion/', body);
export const obtenerTablero = () => apiClient.get('cuentas-por-pagar/tablero/');
export const obtenerProyeccion = () => apiClient.get('cuentas-por-pagar/proyeccion/');
export const obtenerCalendario = (params) => apiClient.get('cuentas-por-pagar/calendario/', { params });
export const obtenerReporte = (informe, params) => apiClient.get(`cuentas-por-pagar/reportes/${informe}/`, { params });
export const listarBandeja = (params = {}) => apiClient.get('cuentas-por-pagar/bandeja/', { params });
export const marcarAvisoLeido = (avisoId) => apiClient.patch(`cuentas-por-pagar/bandeja/${avisoId}/`, { leido: true });
